//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;
using    Renaissance.Protocol.types.game.context.roleplay;

namespace Renaissance.Protocol.messages.game.context.roleplay.npc
{
	public class AllianceTaxCollectorDialogQuestionExtendedMessage : TaxCollectorDialogQuestionExtendedMessage, IDofusMessage
	{
		public new const int NetworkId = 6445;
		public new int ProtocolId { get { return NetworkId; } }

		public BasicNamedAllianceInformations Alliance { get; set; }


		public AllianceTaxCollectorDialogQuestionExtendedMessage() { }


		public AllianceTaxCollectorDialogQuestionExtendedMessage InitAllianceTaxCollectorDialogQuestionExtendedMessage(BasicNamedAllianceInformations _alliance)
		{

			this.Alliance = _alliance;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.Alliance.Serialize();
			size += serialized1.Length;
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Alliance = new BasicNamedAllianceInformations();
			this.Alliance.Deserialize(reader);

		}


	}
}
