//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.npc
{
	public class EntityTalkMessage : IDofusMessage
	{
		public  const int NetworkId = 6110;
		public  int ProtocolId { get { return NetworkId; } }

		public double EntityId { get; set; }

		public CustomVar<short> TextId { get; set; }

		public string[] Parameters { get; set; }


		public EntityTalkMessage() { }


		public EntityTalkMessage InitEntityTalkMessage(double _entityid, CustomVar<short> _textid, string[] _parameters)
		{

			this.EntityId = _entityid;
			this.TextId = _textid;
			this.Parameters = _parameters;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(EntityId);
			size += DofusBinaryFactory.Sizing.SizeOf(TextId);
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.Parameters.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(Parameters);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.EntityId);
			writer.WriteData(this.TextId);
			writer.WriteData((short)(this.Parameters.Length));
			writer.WriteDatas(Parameters);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.EntityId = reader.Read<double>();
			this.TextId = reader.Read<CustomVar<short>>();
			int Parameters_length = reader.Read<short>();
			this.Parameters = new string[Parameters_length];
			for(int i = 0; i < Parameters_length; i++)
				this.Parameters[i] = reader.Read<string>();

		}


	}
}
