//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.npc
{
	public class NpcDialogQuestionMessage : IDofusMessage
	{
		public  const int NetworkId = 5617;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> MessageId { get; set; }

		public string[] DialogParams { get; set; }

		public CustomVar<int>[] VisibleReplies { get; set; }


		public NpcDialogQuestionMessage() { }


		public NpcDialogQuestionMessage InitNpcDialogQuestionMessage(CustomVar<int> _messageid, string[] _dialogparams, CustomVar<int>[] _visiblereplies)
		{

			this.MessageId = _messageid;
			this.DialogParams = _dialogparams;
			this.VisibleReplies = _visiblereplies;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(MessageId);
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.DialogParams.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(DialogParams);
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.VisibleReplies.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(VisibleReplies);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.MessageId);
			writer.WriteData((short)(this.DialogParams.Length));
			writer.WriteDatas(DialogParams);
			writer.WriteData((short)(this.VisibleReplies.Length));
			writer.WriteDatas(VisibleReplies);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MessageId = reader.Read<CustomVar<int>>();
			int DialogParams_length = reader.Read<short>();
			this.DialogParams = new string[DialogParams_length];
			for(int i = 0; i < DialogParams_length; i++)
				this.DialogParams[i] = reader.Read<string>();
			int VisibleReplies_length = reader.Read<short>();
			this.VisibleReplies = new CustomVar<int>[VisibleReplies_length];
			for(int i = 0; i < VisibleReplies_length; i++)
				this.VisibleReplies[i] = reader.Read<CustomVar<int>>();

		}


	}
}
