//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

/* ReSharper disable InconsistentNaming */




namespace StumpR.Protocol.Enums;

public enum AggressableStatusEnum
{
    NON_AGGRESSABLE = 0,

    PvP_ENABLED_AGGRESSABLE = 10,

    PvP_ENABLED_NON_AGGRESSABLE = 11,

    AvA_ENABLED_AGGRESSABLE = 20,

    AvA_ENABLED_NON_AGGRESSABLE = 21,

    AvA_DISQUALIFIED = 22,

    AvA_PREQUALIFIED_AGGRESSABLE = 23
}