//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

/* ReSharper disable InconsistentNaming */




namespace StumpR.Protocol.Enums;

public enum BuildTypeEnum
{
    RELEASE = 0,

    BETA = 1,

    ALPHA = 2,

    TESTING = 3,

    INTERNAL = 4,

    DEBUG = 5,

    DRAFT = 6
}