//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

/* ReSharper disable InconsistentNaming */




namespace StumpR.Protocol.Enums;

public enum DelayedActionTypeEnum
{
    DELAYED_ACTION_DISCONNECT = 0,

    DELAYED_ACTION_OBJECT_USE = 1,

    DELAYED_ACTION_JOIN_CHARACTER = 2,

    DELAYED_ACTION_AGGRESSION_IMMUNE = 3
}