//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

/* ReSharper disable InconsistentNaming */




namespace StumpR.Protocol.Enums;

public enum FightDispellableEnum
{
    DISPELLABLE = 1,

    DISPELLABLE_BY_DEATH = 2,

    DISPELLABLE_BY_STRONG_DISPEL = 3,

    REALLY_NOT_DISPELLABLE = 4
}