//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

/* ReSharper disable InconsistentNaming */




namespace StumpR.Protocol.Enums;

public enum PlayerStatusEnum
{
    PLAYER_STATUS_OFFLINE = 0,

    PLAYER_STATUS_UNKNOWN = 1,

    PLAYER_STATUS_AVAILABLE = 10,

    PLAYER_STATUS_IDLE = 20,

    PLAYER_STATUS_AFK = 21,

    PLAYER_STATUS_PRIVATE = 30,

    PLAYER_STATUS_SOLO = 40
}