//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:09.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.chat
{
	public class ChatAbstractServerMessage : IDofusMessage
	{
		public  const int NetworkId = 880;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Channel { get; set; }

		public string Content { get; set; }

		public int Timestamp { get; set; }

		public string Fingerprint { get; set; }


		public ChatAbstractServerMessage() { }


		public ChatAbstractServerMessage InitChatAbstractServerMessage(byte _channel, string _content, int _timestamp, string _fingerprint)
		{

			this.Channel = _channel;
			this.Content = _content;
			this.Timestamp = _timestamp;
			this.Fingerprint = _fingerprint;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Channel);
			writer.Write(this.Content);
			writer.Write(this.Timestamp);
			writer.Write(this.Fingerprint);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Channel = reader.Read<byte>();
			this.Content = reader.Read<string>();
			this.Timestamp = reader.Read<int>();
			this.Fingerprint = reader.Read<string>();

		}


	}
}
