//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class AbstractPartyMessage : IDofusMessage
	{
		public  const int NetworkId = 6274;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> PartyId { get; set; }


		public AbstractPartyMessage() { }


		public AbstractPartyMessage InitAbstractPartyMessage(CustomVar<int> _partyid)
		{

			this.PartyId = _partyid;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(PartyId);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.PartyId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.PartyId = reader.Read<CustomVar<int>>();

		}


	}
}
