//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:25.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class DungeonPartyFinderListenRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6246;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> DungeonId { get; set; }


		public DungeonPartyFinderListenRequestMessage() { }


		public DungeonPartyFinderListenRequestMessage InitDungeonPartyFinderListenRequestMessage(CustomVar<short> _dungeonid)
		{

			this.DungeonId = _dungeonid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.DungeonId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.DungeonId = reader.Read<CustomVar<short>>();

		}


	}
}
