//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:25.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class PartyInvitationRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 5585;
		public  int ProtocolId { get { return NetworkId; } }

		public string Name { get; set; }


		public PartyInvitationRequestMessage() { }


		public PartyInvitationRequestMessage InitPartyInvitationRequestMessage(string _name)
		{

			this.Name = _name;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Name);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Name = reader.Read<string>();

		}


	}
}
