//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:25.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class PartyKickedByMessage : AbstractPartyMessage, IDofusMessage
	{
		public new const int NetworkId = 5590;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> KickerId { get; set; }


		public PartyKickedByMessage() { }


		public PartyKickedByMessage InitPartyKickedByMessage(CustomVar<long> _kickerid)
		{

			this.KickerId = _kickerid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.KickerId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.KickerId = reader.Read<CustomVar<long>>();

		}


	}
}
