//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:25.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class PartyCannotJoinErrorMessage : AbstractPartyMessage, IDofusMessage
	{
		public new const int NetworkId = 5583;
		public new int ProtocolId { get { return NetworkId; } }

		public byte Reason { get; set; }


		public PartyCannotJoinErrorMessage() { }


		public PartyCannotJoinErrorMessage InitPartyCannotJoinErrorMessage(byte _reason)
		{

			this.Reason = _reason;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Reason);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Reason = reader.Read<byte>();

		}


	}
}
