//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class PartyFollowStatusUpdateMessage : AbstractPartyMessage, IDofusMessage
	{
		public new const int NetworkId = 5581;
		public new int ProtocolId { get { return NetworkId; } }

		public WrappedBool Success { get; set; }

		public WrappedBool IsFollowed { get; set; }

		public CustomVar<long> FollowedId { get; set; }


		public PartyFollowStatusUpdateMessage() { }


		public PartyFollowStatusUpdateMessage InitPartyFollowStatusUpdateMessage(CustomVar<int> _partyid, WrappedBool _success, WrappedBool _isfollowed, CustomVar<long> _followedid)
		{

			base.PartyId = _partyid;
			this.Success = _success;
			this.IsFollowed = _isfollowed;
			this.FollowedId = _followedid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size++;
			size++;
			size += DofusBinaryFactory.Sizing.SizeOf(FollowedId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			byte box = 0;
			box = writer.SetFlag(box,0,this.Success);
			box = writer.SetFlag(box,1,this.IsFollowed);
			writer.WriteData(box);
			writer.WriteData(this.FollowedId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			byte box = reader.Read<byte>();
			this.Success = reader.ReadFlag(box,0);
			this.IsFollowed = reader.ReadFlag(box,1);
			this.FollowedId = reader.Read<CustomVar<long>>();

		}


	}
}
