//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.party
{
	public class PartyKickedByMessage : AbstractPartyMessage, IDofusMessage
	{
		public new const int NetworkId = 5590;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> KickerId { get; set; }


		public PartyKickedByMessage() { }


		public PartyKickedByMessage InitPartyKickedByMessage(CustomVar<int> _partyid, CustomVar<long> _kickerid)
		{

			base.PartyId = _partyid;
			this.KickerId = _kickerid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(KickerId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.KickerId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.KickerId = reader.Read<CustomVar<long>>();

		}


	}
}
