//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.sounds
{
	[D2OClass("SoundBones", "com.ankamagames.dofus.datacenter.sounds")]
	public class SoundBonesData : IDataCenter
	{

		private uint m_id;
		private List<String> m_keys;
		private List<List<SoundAnimationData>> m_values;

		public uint Id
		{
			get => m_id;
			set => m_id = value;
		}

		public List<String> Keys
		{
			get => m_keys;
			set => m_keys = value;
		}

		public List<List<SoundAnimationData>> Values
		{
			get => m_values;
			set => m_values = value;
		}


	}
}
