//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:57.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.alignment.war.effort;

namespace Renaissance.Protocol.messages.game.context.roleplay.alignment.war.effort
{
	public class AlignmentWarEffortProgressionMessage : IDofusMessage
	{
		public  const int NetworkId = 6852;
		public  int ProtocolId { get { return NetworkId; } }

		public AlignmentWarEffortInformation[] EffortProgressions { get; set; }


		public AlignmentWarEffortProgressionMessage() { }


		public AlignmentWarEffortProgressionMessage InitAlignmentWarEffortProgressionMessage(AlignmentWarEffortInformation[] _effortprogressions)
		{

			this.EffortProgressions = _effortprogressions;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.EffortProgressions.Length));
			var memory1 = new Memory<byte>[EffortProgressions.Length];
			for(int i = 0; i < EffortProgressions.Length; i++)
			{
				memory1[i] = this.EffortProgressions[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.EffortProgressions.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int EffortProgressions_length = reader.Read<short>();
			this.EffortProgressions = new AlignmentWarEffortInformation[EffortProgressions_length];
			for(int i = 0; i < EffortProgressions_length; i++)
			{
				this.EffortProgressions[i] = new AlignmentWarEffortInformation();
				this.EffortProgressions[i].Deserialize(reader);
			}

		}


	}
}
