//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:46.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.pvp
{
	public class AlignmentRankUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 6058;
		public  int ProtocolId { get { return NetworkId; } }

		public byte AlignmentRank { get; set; }

		public bool Verbose { get; set; }


		public AlignmentRankUpdateMessage() { }


		public AlignmentRankUpdateMessage InitAlignmentRankUpdateMessage(byte _alignmentrank, bool _verbose)
		{

			this.AlignmentRank = _alignmentrank;
			this.Verbose = _verbose;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(AlignmentRank);
			size += DofusBinaryFactory.Sizing.SizeOf(Verbose);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.AlignmentRank);
			writer.WriteData(this.Verbose);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.AlignmentRank = reader.Read<byte>();
			this.Verbose = reader.Read<bool>();

		}


	}
}
