//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;
using    Renaissance.Protocol.datacenter.items.criterion;

namespace Renaissance.Protocol.datacenter.quest
{
	[D2OClass("Quest", "com.ankamagames.dofus.datacenter.quest")]
	public class QuestData : IDataCenter
	{

		private uint m_id;
		private uint m_nameId;
		private List<uint> m_stepIds;
		private uint m_categoryId;
		private uint m_repeatType;
		private uint m_repeatLimit;
		private Boolean m_isDungeonQuest;
		private uint m_levelMin;
		private uint m_levelMax;
		private Boolean m_isPartyQuest;
		private String m_startCriterion;
		private Boolean m_followable;

		public uint Id
		{
			get => m_id;
			set => m_id = value;
		}

		public uint NameId
		{
			get => m_nameId;
			set => m_nameId = value;
		}

		public List<uint> StepIds
		{
			get => m_stepIds;
			set => m_stepIds = value;
		}

		public uint CategoryId
		{
			get => m_categoryId;
			set => m_categoryId = value;
		}

		public uint RepeatType
		{
			get => m_repeatType;
			set => m_repeatType = value;
		}

		public uint RepeatLimit
		{
			get => m_repeatLimit;
			set => m_repeatLimit = value;
		}

		public Boolean IsDungeonQuest
		{
			get => m_isDungeonQuest;
			set => m_isDungeonQuest = value;
		}

		public uint LevelMin
		{
			get => m_levelMin;
			set => m_levelMin = value;
		}

		public uint LevelMax
		{
			get => m_levelMax;
			set => m_levelMax = value;
		}

		public Boolean IsPartyQuest
		{
			get => m_isPartyQuest;
			set => m_isPartyQuest = value;
		}

		public String StartCriterion
		{
			get => m_startCriterion;
			set => m_startCriterion = value;
		}

		public Boolean Followable
		{
			get => m_followable;
			set => m_followable = value;
		}


	}
}
