//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;
using    Renaissance.Protocol.datacenter.npcs;
using    Renaissance.Protocol.datacenter.quest.objectives;

namespace Renaissance.Protocol.datacenter.quest
{
	[D2OClass("QuestObjective", "com.ankamagames.dofus.datacenter.quest")]
	public class QuestObjectiveData : IDataCenter
	{

		private uint m_id;
		private uint m_stepId;
		private uint m_typeId;
		private int m_dialogId;
		private QuestObjectiveParametersData m_parameters;
		private Point m_coords;
		private double m_mapId;

		public uint Id
		{
			get => m_id;
			set => m_id = value;
		}

		public uint StepId
		{
			get => m_stepId;
			set => m_stepId = value;
		}

		public uint TypeId
		{
			get => m_typeId;
			set => m_typeId = value;
		}

		public int DialogId
		{
			get => m_dialogId;
			set => m_dialogId = value;
		}

		public QuestObjectiveParametersData Parameters
		{
			get => m_parameters;
			set => m_parameters = value;
		}

		public Point Coords
		{
			get => m_coords;
			set => m_coords = value;
		}

		public double MapId
		{
			get => m_mapId;
			set => m_mapId = value;
		}


	}
}
