//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class HavenbagFurniture
{

    public int TypeId { get; set; }

    public int ThemeId { get; set; }

    public int ElementId { get; set; }

    public int Color { get; set; }

    public int SkillId { get; set; }

    public int LayerId { get; set; }

    public bool BlocksMovement { get; set; }

    public bool IsStackable { get; set; }

    public uint CellsWidth { get; set; }

    public uint CellsHeight { get; set; }

    public uint Order { get; set; }

}