//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;
using    Renaissance.Protocol.types.game.mount;

namespace Renaissance.Protocol.types.game.paddock
{
	public class PaddockItem : ObjectItemInRolePlay, IDofusType
	{
		public new const int NetworkId = 185;
		public new int ProtocolId { get { return NetworkId; } }

		public ItemDurability Durability { get; set; }


		public PaddockItem() { }


		public PaddockItem InitPaddockItem(ItemDurability _durability)
		{

			this.Durability = _durability;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Durability.Serialize());

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Durability = new ItemDurability();
			this.Durability.Deserialize(reader);

		}


	}
}
