// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renaissance.World.Database.Achievements.Rewards;

namespace Renaissance.World.Migrations.AchievementReward
{
    [DbContext(typeof(AchievementRewardContext))]
    [Migration("20191228181258_AchievementsPatched")]
    partial class AchievementsPatched
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Renaissance.World.Database.Achievements.Rewards.AchievementReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<string>("Criteria")
                        .HasColumnType("text");

                    b.Property<List<int>>("EmotesReward")
                        .HasColumnType("integer[]");

                    b.Property<double>("ExperienceRatio")
                        .HasColumnType("double precision");

                    b.Property<List<int>>("ItemsQuantityReward")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("ItemsReward")
                        .HasColumnType("integer[]");

                    b.Property<double>("KamasRatio")
                        .HasColumnType("double precision");

                    b.Property<bool>("KamasScaleWithPlayerLevel")
                        .HasColumnType("boolean");

                    b.Property<List<int>>("OrnamentsReward")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("SpellsReward")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("TitlesReward")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("AchievementsRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
