//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.web.haapi
{
	public class HaapiBuyValidationMessage : HaapiValidationMessage, IDofusMessage
	{
		public new const int NetworkId = 6841;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> Amount { get; set; }

		public string Email { get; set; }


		public HaapiBuyValidationMessage() { }


		public HaapiBuyValidationMessage InitHaapiBuyValidationMessage(CustomVar<long> _amount, string _email)
		{

			this.Amount = _amount;
			this.Email = _email;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Amount);
			size += DofusBinaryFactory.Sizing.SizeOf(Email);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Amount);
			writer.WriteData(this.Email);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Amount = reader.Read<CustomVar<long>>();
			this.Email = reader.Read<string>();

		}


	}
}
