//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:42.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;
using    Renaissance.Protocol.types.game.social;

namespace Renaissance.Protocol.messages.game.alliance
{
	public class AllianceFactsMessage : IDofusMessage
	{
		public  const int NetworkId = 6414;
		public  int ProtocolId { get { return NetworkId; } }

		public AllianceFactSheetInformations Infos { get; set; }

		public GuildInAllianceInformations[] Guilds { get; set; }

		public CustomVar<short>[] ControlledSubareaIds { get; set; }

		public CustomVar<long> LeaderCharacterId { get; set; }

		public string LeaderCharacterName { get; set; }


		public AllianceFactsMessage() { }


		public AllianceFactsMessage InitAllianceFactsMessage(AllianceFactSheetInformations _infos, GuildInAllianceInformations[] _guilds, CustomVar<short>[] _controlledsubareaids, CustomVar<long> _leadercharacterid, string _leadercharactername)
		{

			this.Infos = _infos;
			this.Guilds = _guilds;
			this.ControlledSubareaIds = _controlledsubareaids;
			this.LeaderCharacterId = _leadercharacterid;
			this.LeaderCharacterName = _leadercharactername;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += 2;
			var serialized1 = this.Infos.Serialize();
			size += serialized1.Length;
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.Guilds.Length));
			var memory1 = new Memory<byte>[Guilds.Length];
			for(int i = 0; i < Guilds.Length; i++)
			{
				memory1[i] = this.Guilds[i].Serialize();
				size += memory1[i].Length;
			}
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.ControlledSubareaIds.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(ControlledSubareaIds);
			size += DofusBinaryFactory.Sizing.SizeOf(LeaderCharacterId);
			size += DofusBinaryFactory.Sizing.SizeOf(LeaderCharacterName);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(Infos.ProtocolId));
			writer.WriteDatas(serialized1);
			writer.WriteData((short)(this.Guilds.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}
			writer.WriteData((short)(this.ControlledSubareaIds.Length));
			writer.WriteDatas(ControlledSubareaIds);
			writer.WriteData(this.LeaderCharacterId);
			writer.WriteData(this.LeaderCharacterName);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			reader.Skip(2); // skip protocolManager.GetInstance(short)
			this.Infos = new AllianceFactSheetInformations();
			this.Infos.Deserialize(reader);
			int Guilds_length = reader.Read<short>();
			this.Guilds = new GuildInAllianceInformations[Guilds_length];
			for(int i = 0; i < Guilds_length; i++)
			{
				this.Guilds[i] = new GuildInAllianceInformations();
				this.Guilds[i].Deserialize(reader);
			}
			int ControlledSubareaIds_length = reader.Read<short>();
			this.ControlledSubareaIds = new CustomVar<short>[ControlledSubareaIds_length];
			for(int i = 0; i < ControlledSubareaIds_length; i++)
				this.ControlledSubareaIds[i] = reader.Read<CustomVar<short>>();
			this.LeaderCharacterId = reader.Read<CustomVar<long>>();
			this.LeaderCharacterName = reader.Read<string>();

		}


	}
}
