//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:42.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.alliance
{
	public class AllianceGuildLeavingMessage : IDofusMessage
	{
		public  const int NetworkId = 6399;
		public  int ProtocolId { get { return NetworkId; } }

		public bool Kicked { get; set; }

		public CustomVar<int> GuildId { get; set; }


		public AllianceGuildLeavingMessage() { }


		public AllianceGuildLeavingMessage InitAllianceGuildLeavingMessage(bool _kicked, CustomVar<int> _guildid)
		{

			this.Kicked = _kicked;
			this.GuildId = _guildid;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Kicked);
			size += DofusBinaryFactory.Sizing.SizeOf(GuildId);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Kicked);
			writer.WriteData(this.GuildId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Kicked = reader.Read<bool>();
			this.GuildId = reader.Read<CustomVar<int>>();

		}


	}
}
