//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:42.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.alliance
{
	public class AllianceInvitationStateRecruterMessage : IDofusMessage
	{
		public  const int NetworkId = 6396;
		public  int ProtocolId { get { return NetworkId; } }

		public string RecrutedName { get; set; }

		public byte InvitationState { get; set; }


		public AllianceInvitationStateRecruterMessage() { }


		public AllianceInvitationStateRecruterMessage InitAllianceInvitationStateRecruterMessage(string _recrutedname, byte _invitationstate)
		{

			this.RecrutedName = _recrutedname;
			this.InvitationState = _invitationstate;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(RecrutedName);
			size += DofusBinaryFactory.Sizing.SizeOf(InvitationState);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.RecrutedName);
			writer.WriteData(this.InvitationState);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.RecrutedName = reader.Read<string>();
			this.InvitationState = reader.Read<byte>();

		}


	}
}
