//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:48.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.atlas.compass
{
	public class CompassResetMessage : IDofusMessage
	{
		public  const int NetworkId = 5584;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Type { get; set; }


		public CompassResetMessage() { }


		public CompassResetMessage InitCompassResetMessage(byte _type)
		{

			this.Type = _type;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Type);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Type);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Type = reader.Read<byte>();

		}


	}
}
