//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.lockable
{
	public class LockableStateUpdateHouseDoorMessage : LockableStateUpdateAbstractMessage, IDofusMessage
	{
		public new const int NetworkId = 5668;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> HouseId { get; set; }

		public int InstanceId { get; set; }

		public bool SecondHand { get; set; }


		public LockableStateUpdateHouseDoorMessage() { }


		public LockableStateUpdateHouseDoorMessage InitLockableStateUpdateHouseDoorMessage(bool _locked, CustomVar<int> _houseid, int _instanceid, bool _secondhand)
		{

			base.Locked = _locked;
			this.HouseId = _houseid;
			this.InstanceId = _instanceid;
			this.SecondHand = _secondhand;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(HouseId);
			size += DofusBinaryFactory.Sizing.SizeOf(InstanceId);
			size += DofusBinaryFactory.Sizing.SizeOf(SecondHand);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.HouseId);
			writer.WriteData(this.InstanceId);
			writer.WriteData(this.SecondHand);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.HouseId = reader.Read<CustomVar<int>>();
			this.InstanceId = reader.Read<int>();
			this.SecondHand = reader.Read<bool>();

		}


	}
}
