//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:10.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.dare
{
	public class DareRewardConsumeRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6676;
		public  int ProtocolId { get { return NetworkId; } }

		public double DareId { get; set; }

		public byte Type { get; set; }


		public DareRewardConsumeRequestMessage() { }


		public DareRewardConsumeRequestMessage InitDareRewardConsumeRequestMessage(double _dareid, byte _type)
		{

			this.DareId = _dareid;
			this.Type = _type;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.DareId);
			writer.Write(this.Type);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.DareId = reader.Read<double>();
			this.Type = reader.Read<byte>();

		}


	}
}
