//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:44.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.dare
{
	public class DareSubscribeRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6666;
		public  int ProtocolId { get { return NetworkId; } }

		public double DareId { get; set; }

		public bool Subscribe { get; set; }


		public DareSubscribeRequestMessage() { }


		public DareSubscribeRequestMessage InitDareSubscribeRequestMessage(double _dareid, bool _subscribe)
		{

			this.DareId = _dareid;
			this.Subscribe = _subscribe;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(DareId);
			size += DofusBinaryFactory.Sizing.SizeOf(Subscribe);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.DareId);
			writer.WriteData(this.Subscribe);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.DareId = reader.Read<double>();
			this.Subscribe = reader.Read<bool>();

		}


	}
}
