//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:27.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.achievement
{
	public class AchievementStartedObjective : AchievementObjective, IDofusType
	{
		public new const int NetworkId = 402;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Value { get; set; }


		public AchievementStartedObjective() { }


		public AchievementStartedObjective InitAchievementStartedObjective(CustomVar<short> _value)
		{

			this.Value = _value;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Value);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Value = reader.Read<CustomVar<short>>();

		}


	}
}
