//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:24.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.house;

namespace Renaissance.Protocol.messages.game.context.roleplay.houses
{
	public class AccountHouseMessage : IDofusMessage
	{
		public  const int NetworkId = 6315;
		public  int ProtocolId { get { return NetworkId; } }

		public AccountHouseInformations[] Houses { get; set; }


		public AccountHouseMessage() { }


		public AccountHouseMessage InitAccountHouseMessage(AccountHouseInformations[] _houses)
		{

			this.Houses = _houses;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Houses.Length));
			foreach(var obj in Houses)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Houses_length = reader.Read<short>();
			this.Houses = new AccountHouseInformations[Houses_length];
			for(int i = 0; i < Houses_length; i++)
			{
				this.Houses[i] = new AccountHouseInformations();
				this.Houses[i].Deserialize(reader);
			}

		}


	}
}
