//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:23.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context;

namespace Renaissance.Protocol.messages.game.context.fight.character
{
	public class GameFightRefreshFighterMessage : IDofusMessage
	{
		public  const int NetworkId = 6309;
		public  int ProtocolId { get { return NetworkId; } }

		public GameContextActorInformations Informations { get; set; }


		public GameFightRefreshFighterMessage() { }


		public GameFightRefreshFighterMessage InitGameFightRefreshFighterMessage(GameContextActorInformations _informations)
		{

			this.Informations = _informations;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(Informations.ProtocolId));
			writer.Write(this.Informations.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

reader.Skip(2); // skip read short
			this.Informations = new GameContextActorInformations();
			this.Informations.Deserialize(reader);

		}


	}
}
