//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:58.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.house
{
	public class HouseInformations : IDofusType
	{
		public  const int NetworkId = 111;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> HouseId { get; set; }

		public CustomVar<short> ModelId { get; set; }


		public HouseInformations() { }


		public HouseInformations InitHouseInformations(CustomVar<int> _houseid, CustomVar<short> _modelid)
		{

			this.HouseId = _houseid;
			this.ModelId = _modelid;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(HouseId);
			size += DofusBinaryFactory.Sizing.SizeOf(ModelId);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.HouseId);
			writer.WriteData(this.ModelId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.HouseId = reader.Read<CustomVar<int>>();
			this.ModelId = reader.Read<CustomVar<short>>();

		}


	}
}
