//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:58.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;

namespace Renaissance.Protocol.types.game.house
{
	public class HouseGuildedInformations : HouseInstanceInformations, IDofusType
	{
		public new const int NetworkId = 512;
		public new int ProtocolId { get { return NetworkId; } }

		public GuildInformations GuildInfo { get; set; }


		public HouseGuildedInformations() { }


		public HouseGuildedInformations InitHouseGuildedInformations(GuildInformations _guildinfo)
		{

			this.GuildInfo = _guildinfo;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.GuildInfo.Serialize();
			size += serialized1.Length;
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.GuildInfo = new GuildInformations();
			this.GuildInfo.Deserialize(reader);

		}


	}
}
