//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:58.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.mount
{
	public class ItemDurability : IDofusType
	{
		public  const int NetworkId = 168;
		public  int ProtocolId { get { return NetworkId; } }

		public short Durability { get; set; }

		public short DurabilityMax { get; set; }


		public ItemDurability() { }


		public ItemDurability InitItemDurability(short _durability, short _durabilitymax)
		{

			this.Durability = _durability;
			this.DurabilityMax = _durabilitymax;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Durability);
			size += DofusBinaryFactory.Sizing.SizeOf(DurabilityMax);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Durability);
			writer.WriteData(this.DurabilityMax);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Durability = reader.Read<short>();
			this.DurabilityMax = reader.Read<short>();

		}


	}
}
