//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:54.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.emote
{
	public class EmotePlayMassiveMessage : EmotePlayAbstractMessage, IDofusMessage
	{
		public new const int NetworkId = 5691;
		public new int ProtocolId { get { return NetworkId; } }

		public double[] ActorIds { get; set; }


		public EmotePlayMassiveMessage() { }


		public EmotePlayMassiveMessage InitEmotePlayMassiveMessage(byte _emoteid, double _emotestarttime, double[] _actorids)
		{

			base.EmoteId = _emoteid;
			base.EmoteStartTime = _emotestarttime;
			this.ActorIds = _actorids;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.ActorIds.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(ActorIds);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData((short)(this.ActorIds.Length));
			writer.WriteDatas(ActorIds);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			int ActorIds_length = reader.Read<short>();
			this.ActorIds = new double[ActorIds_length];
			for(int i = 0; i < ActorIds_length; i++)
				this.ActorIds[i] = reader.Read<double>();

		}


	}
}
