//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.effects
{
	[D2OClass("Effect", "com.ankamagames.dofus.datacenter.effects")]
	public class EffectData : IDataCenter
	{

		private int m_id;
		private uint m_descriptionId;
		private uint m_iconId;
		private int m_characteristic;
		private uint m_category;
		private String m_operator;
		private Boolean m_showInTooltip;
		private Boolean m_useDice;
		private Boolean m_forceMinMax;
		private Boolean m_boost;
		private Boolean m_active;
		private int m_oppositeId;
		private uint m_theoreticalDescriptionId;
		private uint m_theoreticalPattern;
		private Boolean m_showInSet;
		private int m_bonusType;
		private Boolean m_useInFight;
		private uint m_effectPriority;
		private int m_elementId;

		public int Id
		{
			get => m_id;
			set => m_id = value;
		}

		public uint DescriptionId
		{
			get => m_descriptionId;
			set => m_descriptionId = value;
		}

		public uint IconId
		{
			get => m_iconId;
			set => m_iconId = value;
		}

		public int Characteristic
		{
			get => m_characteristic;
			set => m_characteristic = value;
		}

		public uint Category
		{
			get => m_category;
			set => m_category = value;
		}

		public String Operator
		{
			get => m_operator;
			set => m_operator = value;
		}

		public Boolean ShowInTooltip
		{
			get => m_showInTooltip;
			set => m_showInTooltip = value;
		}

		public Boolean UseDice
		{
			get => m_useDice;
			set => m_useDice = value;
		}

		public Boolean ForceMinMax
		{
			get => m_forceMinMax;
			set => m_forceMinMax = value;
		}

		public Boolean Boost
		{
			get => m_boost;
			set => m_boost = value;
		}

		public Boolean Active
		{
			get => m_active;
			set => m_active = value;
		}

		public int OppositeId
		{
			get => m_oppositeId;
			set => m_oppositeId = value;
		}

		public uint TheoreticalDescriptionId
		{
			get => m_theoreticalDescriptionId;
			set => m_theoreticalDescriptionId = value;
		}

		public uint TheoreticalPattern
		{
			get => m_theoreticalPattern;
			set => m_theoreticalPattern = value;
		}

		public Boolean ShowInSet
		{
			get => m_showInSet;
			set => m_showInSet = value;
		}

		public int BonusType
		{
			get => m_bonusType;
			set => m_bonusType = value;
		}

		public Boolean UseInFight
		{
			get => m_useInFight;
			set => m_useInFight = value;
		}

		public uint EffectPriority
		{
			get => m_effectPriority;
			set => m_effectPriority = value;
		}

		public int ElementId
		{
			get => m_elementId;
			set => m_elementId = value;
		}


	}
}
