//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:31.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.data.items.effects
{
	public class ObjectEffectCreature : ObjectEffect, IDofusType
	{
		public new const int NetworkId = 71;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> MonsterFamilyId { get; set; }


		public ObjectEffectCreature() { }


		public ObjectEffectCreature InitObjectEffectCreature(CustomVar<short> _monsterfamilyid)
		{

			this.MonsterFamilyId = _monsterfamilyid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.MonsterFamilyId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.MonsterFamilyId = reader.Read<CustomVar<short>>();

		}


	}
}
