//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:02.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.data.items.effects
{
	public class ObjectEffectDuration : ObjectEffect, IDofusType
	{
		public new const int NetworkId = 75;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Days { get; set; }

		public byte Hours { get; set; }

		public byte Minutes { get; set; }


		public ObjectEffectDuration() { }


		public ObjectEffectDuration InitObjectEffectDuration(CustomVar<short> _actionid, CustomVar<short> _days, byte _hours, byte _minutes)
		{

			base.ActionId = _actionid;
			this.Days = _days;
			this.Hours = _hours;
			this.Minutes = _minutes;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Days);
			size += DofusBinaryFactory.Sizing.SizeOf(Hours);
			size += DofusBinaryFactory.Sizing.SizeOf(Minutes);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Days);
			writer.WriteData(this.Hours);
			writer.WriteData(this.Minutes);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Days = reader.Read<CustomVar<short>>();
			this.Hours = reader.Read<byte>();
			this.Minutes = reader.Read<byte>();

		}


	}
}
