//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:32.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.data.items.effects
{
	public class ObjectEffectMinMax : ObjectEffect, IDofusType
	{
		public new const int NetworkId = 82;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> Min { get; set; }

		public CustomVar<int> Max { get; set; }


		public ObjectEffectMinMax() { }


		public ObjectEffectMinMax InitObjectEffectMinMax(CustomVar<int> _min, CustomVar<int> _max)
		{

			this.Min = _min;
			this.Max = _max;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Min);
			writer.Write(this.Max);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Min = reader.Read<CustomVar<int>>();
			this.Max = reader.Read<CustomVar<int>>();

		}


	}
}
