//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:11.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guest
{
	public class GuestModeMessage : IDofusMessage
	{
		public  const int NetworkId = 6505;
		public  int ProtocolId { get { return NetworkId; } }

		public bool Active { get; set; }


		public GuestModeMessage() { }


		public GuestModeMessage InitGuestModeMessage(bool _active)
		{

			this.Active = _active;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Active);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Active = reader.Read<bool>();

		}


	}
}
