//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class EffectInstanceMount: EffectInstance
{

    public double Id { get; set; }

    public double ExpirationDate { get; set; }

    public uint Model { get; set; }

    public string Name { get; set; }

    public string Owner { get; set; }

    public uint Level { get; set; }

    public bool Sex { get; set; }

    public bool IsRideable { get; set; }

    public bool IsFeconded { get; set; }

    public bool IsFecondationReady { get; set; }

    public int ReproductionCount { get; set; }

    public uint ReproductionCountMax { get; set; }

    public List<EffectInstanceInteger> Effects { get; set; }

    public List<uint> Capacities { get; set; }

}