//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:00.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.roleplay
{
	public class AlternativeMonstersInGroupLightInformations : IDofusType
	{
		public  const int NetworkId = 394;
		public  int ProtocolId { get { return NetworkId; } }

		public int PlayerCount { get; set; }

		public MonsterInGroupLightInformations[] Monsters { get; set; }


		public AlternativeMonstersInGroupLightInformations() { }


		public AlternativeMonstersInGroupLightInformations InitAlternativeMonstersInGroupLightInformations(int _playercount, MonsterInGroupLightInformations[] _monsters)
		{

			this.PlayerCount = _playercount;
			this.Monsters = _monsters;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(PlayerCount);
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.Monsters.Length));
			var memory1 = new Memory<byte>[Monsters.Length];
			for(int i = 0; i < Monsters.Length; i++)
			{
				memory1[i] = this.Monsters[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.PlayerCount);
			writer.WriteData((short)(this.Monsters.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.PlayerCount = reader.Read<int>();
			int Monsters_length = reader.Read<short>();
			this.Monsters = new MonsterInGroupLightInformations[Monsters_length];
			for(int i = 0; i < Monsters_length; i++)
			{
				this.Monsters[i] = new MonsterInGroupLightInformations();
				this.Monsters[i].Deserialize(reader);
			}

		}


	}
}
