//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:30.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context;
using    Renaissance.Protocol.types.game.look;

namespace Renaissance.Protocol.types.game.context.roleplay
{
	public class GameRolePlayMountInformations : GameRolePlayNamedActorInformations, IDofusType
	{
		public new const int NetworkId = 180;
		public new int ProtocolId { get { return NetworkId; } }

		public string OwnerName { get; set; }

		public byte Level { get; set; }


		public GameRolePlayMountInformations() { }


		public GameRolePlayMountInformations InitGameRolePlayMountInformations(string _ownername, byte _level)
		{

			this.OwnerName = _ownername;
			this.Level = _level;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.OwnerName);
			writer.Write(this.Level);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.OwnerName = reader.Read<string>();
			this.Level = reader.Read<byte>();

		}


	}
}
