//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:30.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context;
using    Renaissance.Protocol.types.game.look;

namespace Renaissance.Protocol.types.game.context.roleplay
{
	public class GameRolePlayMerchantInformations : GameRolePlayNamedActorInformations, IDofusType
	{
		public new const int NetworkId = 129;
		public new int ProtocolId { get { return NetworkId; } }

		public byte SellType { get; set; }

		public HumanOption[] Options { get; set; }


		public GameRolePlayMerchantInformations() { }


		public GameRolePlayMerchantInformations InitGameRolePlayMerchantInformations(byte _selltype, HumanOption[] _options)
		{

			this.SellType = _selltype;
			this.Options = _options;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.SellType);
			writer.Write((short)(this.Options.Length));
			foreach(var obj in Options)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.SellType = reader.Read<byte>();
			int Options_length = reader.Read<short>();
			this.Options = new HumanOption[Options_length];
			for(int i = 0; i < Options_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.Options[i] = new HumanOption();
				this.Options[i].Deserialize(reader);
			}

		}


	}
}
