//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:01.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.roleplay
{
	public class HumanOptionSkillUse : HumanOption, IDofusType
	{
		public new const int NetworkId = 495;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> ElementId { get; set; }

		public CustomVar<short> SkillId { get; set; }

		public double SkillEndTime { get; set; }


		public HumanOptionSkillUse() { }


		public HumanOptionSkillUse InitHumanOptionSkillUse(CustomVar<int> _elementid, CustomVar<short> _skillid, double _skillendtime)
		{

			this.ElementId = _elementid;
			this.SkillId = _skillid;
			this.SkillEndTime = _skillendtime;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(ElementId);
			size += DofusBinaryFactory.Sizing.SizeOf(SkillId);
			size += DofusBinaryFactory.Sizing.SizeOf(SkillEndTime);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.ElementId);
			writer.WriteData(this.SkillId);
			writer.WriteData(this.SkillEndTime);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.ElementId = reader.Read<CustomVar<int>>();
			this.SkillId = reader.Read<CustomVar<short>>();
			this.SkillEndTime = reader.Read<double>();

		}


	}
}
