//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:51.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.job;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class DecraftResultMessage : IDofusMessage
	{
		public  const int NetworkId = 6569;
		public  int ProtocolId { get { return NetworkId; } }

		public DecraftedItemStackInfo[] Results { get; set; }


		public DecraftResultMessage() { }


		public DecraftResultMessage InitDecraftResultMessage(DecraftedItemStackInfo[] _results)
		{

			this.Results = _results;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.Results.Length));
			var memory1 = new Memory<byte>[Results.Length];
			for(int i = 0; i < Results.Length; i++)
			{
				memory1[i] = this.Results[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.Results.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Results_length = reader.Read<short>();
			this.Results = new DecraftedItemStackInfo[Results_length];
			for(int i = 0; i < Results_length; i++)
			{
				this.Results[i] = new DecraftedItemStackInfo();
				this.Results[i].Deserialize(reader);
			}

		}


	}
}
