//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:52.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeWeightMessage : IDofusMessage
	{
		public  const int NetworkId = 5793;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> CurrentWeight { get; set; }

		public CustomVar<int> MaxWeight { get; set; }


		public ExchangeWeightMessage() { }


		public ExchangeWeightMessage InitExchangeWeightMessage(CustomVar<int> _currentweight, CustomVar<int> _maxweight)
		{

			this.CurrentWeight = _currentweight;
			this.MaxWeight = _maxweight;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(CurrentWeight);
			size += DofusBinaryFactory.Sizing.SizeOf(MaxWeight);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.CurrentWeight);
			writer.WriteData(this.MaxWeight);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.CurrentWeight = reader.Read<CustomVar<int>>();
			this.MaxWeight = reader.Read<CustomVar<int>>();

		}


	}
}
