//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangePlayerMultiCraftRequestMessage : ExchangeRequestMessage, IDofusMessage
	{
		public new const int NetworkId = 5784;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> Target { get; set; }

		public CustomVar<int> SkillId { get; set; }


		public ExchangePlayerMultiCraftRequestMessage() { }


		public ExchangePlayerMultiCraftRequestMessage InitExchangePlayerMultiCraftRequestMessage(CustomVar<long> _target, CustomVar<int> _skillid)
		{

			this.Target = _target;
			this.SkillId = _skillid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Target);
			writer.Write(this.SkillId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Target = reader.Read<CustomVar<long>>();
			this.SkillId = reader.Read<CustomVar<int>>();

		}


	}
}
