//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.messages.game.dialog;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeLeaveMessage : LeaveDialogMessage, IDofusMessage
	{
		public new const int NetworkId = 5628;
		public new int ProtocolId { get { return NetworkId; } }

		public bool Success { get; set; }


		public ExchangeLeaveMessage() { }


		public ExchangeLeaveMessage InitExchangeLeaveMessage(bool _success)
		{

			this.Success = _success;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Success);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Success = reader.Read<bool>();

		}


	}
}
