//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:51.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeCraftResultWithObjectIdMessage : ExchangeCraftResultMessage, IDofusMessage
	{
		public new const int NetworkId = 6000;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> ObjectGenericId { get; set; }


		public ExchangeCraftResultWithObjectIdMessage() { }


		public ExchangeCraftResultWithObjectIdMessage InitExchangeCraftResultWithObjectIdMessage(byte _craftresult, CustomVar<short> _objectgenericid)
		{

			base.CraftResult = _craftresult;
			this.ObjectGenericId = _objectgenericid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(ObjectGenericId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.ObjectGenericId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.ObjectGenericId = reader.Read<CustomVar<short>>();

		}


	}
}
