//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeBidHouseUnsoldItemsMessage : IDofusMessage
	{
		public  const int NetworkId = 6612;
		public  int ProtocolId { get { return NetworkId; } }

		public ObjectItemGenericQuantity[] Items { get; set; }


		public ExchangeBidHouseUnsoldItemsMessage() { }


		public ExchangeBidHouseUnsoldItemsMessage InitExchangeBidHouseUnsoldItemsMessage(ObjectItemGenericQuantity[] _items)
		{

			this.Items = _items;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Items.Length));
			foreach(var obj in Items)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Items_length = reader.Read<short>();
			this.Items = new ObjectItemGenericQuantity[Items_length];
			for(int i = 0; i < Items_length; i++)
			{
				this.Items[i] = new ObjectItemGenericQuantity();
				this.Items[i].Deserialize(reader);
			}

		}


	}
}
