//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeGuildTaxCollectorGetMessage : IDofusMessage
	{
		public  const int NetworkId = 5762;
		public  int ProtocolId { get { return NetworkId; } }

		public string CollectorName { get; set; }

		public short WorldX { get; set; }

		public short WorldY { get; set; }

		public double MapId { get; set; }

		public CustomVar<short> SubAreaId { get; set; }

		public string UserName { get; set; }

		public CustomVar<long> CallerId { get; set; }

		public string CallerName { get; set; }

		public double Experience { get; set; }

		public CustomVar<short> Pods { get; set; }

		public ObjectItemGenericQuantity[] ObjectsInfos { get; set; }


		public ExchangeGuildTaxCollectorGetMessage() { }


		public ExchangeGuildTaxCollectorGetMessage InitExchangeGuildTaxCollectorGetMessage(string _collectorname, short _worldx, short _worldy, double _mapid, CustomVar<short> _subareaid, string _username, CustomVar<long> _callerid, string _callername, double _experience, CustomVar<short> _pods, ObjectItemGenericQuantity[] _objectsinfos)
		{

			this.CollectorName = _collectorname;
			this.WorldX = _worldx;
			this.WorldY = _worldy;
			this.MapId = _mapid;
			this.SubAreaId = _subareaid;
			this.UserName = _username;
			this.CallerId = _callerid;
			this.CallerName = _callername;
			this.Experience = _experience;
			this.Pods = _pods;
			this.ObjectsInfos = _objectsinfos;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.CollectorName);
			writer.Write(this.WorldX);
			writer.Write(this.WorldY);
			writer.Write(this.MapId);
			writer.Write(this.SubAreaId);
			writer.Write(this.UserName);
			writer.Write(this.CallerId);
			writer.Write(this.CallerName);
			writer.Write(this.Experience);
			writer.Write(this.Pods);
			writer.Write((short)(this.ObjectsInfos.Length));
			foreach(var obj in ObjectsInfos)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.CollectorName = reader.Read<string>();
			this.WorldX = reader.Read<short>();
			this.WorldY = reader.Read<short>();
			this.MapId = reader.Read<double>();
			this.SubAreaId = reader.Read<CustomVar<short>>();
			this.UserName = reader.Read<string>();
			this.CallerId = reader.Read<CustomVar<long>>();
			this.CallerName = reader.Read<string>();
			this.Experience = reader.Read<double>();
			this.Pods = reader.Read<CustomVar<short>>();
			int ObjectsInfos_length = reader.Read<short>();
			this.ObjectsInfos = new ObjectItemGenericQuantity[ObjectsInfos_length];
			for(int i = 0; i < ObjectsInfos_length; i++)
			{
				this.ObjectsInfos[i] = new ObjectItemGenericQuantity();
				this.ObjectsInfos[i].Deserialize(reader);
			}

		}


	}
}
