//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:51.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeBidHouseInListRemovedMessage : IDofusMessage
	{
		public  const int NetworkId = 5950;
		public  int ProtocolId { get { return NetworkId; } }

		public int ItemUID { get; set; }

		public CustomVar<short> ObjectGID { get; set; }

		public int ObjectType { get; set; }


		public ExchangeBidHouseInListRemovedMessage() { }


		public ExchangeBidHouseInListRemovedMessage InitExchangeBidHouseInListRemovedMessage(int _itemuid, CustomVar<short> _objectgid, int _objecttype)
		{

			this.ItemUID = _itemuid;
			this.ObjectGID = _objectgid;
			this.ObjectType = _objecttype;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(ItemUID);
			size += DofusBinaryFactory.Sizing.SizeOf(ObjectGID);
			size += DofusBinaryFactory.Sizing.SizeOf(ObjectType);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.ItemUID);
			writer.WriteData(this.ObjectGID);
			writer.WriteData(this.ObjectType);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ItemUID = reader.Read<int>();
			this.ObjectGID = reader.Read<CustomVar<short>>();
			this.ObjectType = reader.Read<int>();

		}


	}
}
