//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangeShopStockMultiMovementUpdatedMessage : IDofusMessage
	{
		public  const int NetworkId = 6038;
		public  int ProtocolId { get { return NetworkId; } }

		public ObjectItemToSell[] ObjectInfoList { get; set; }


		public ExchangeShopStockMultiMovementUpdatedMessage() { }


		public ExchangeShopStockMultiMovementUpdatedMessage InitExchangeShopStockMultiMovementUpdatedMessage(ObjectItemToSell[] _objectinfolist)
		{

			this.ObjectInfoList = _objectinfolist;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.ObjectInfoList.Length));
			foreach(var obj in ObjectInfoList)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int ObjectInfoList_length = reader.Read<short>();
			this.ObjectInfoList = new ObjectItemToSell[ObjectInfoList_length];
			for(int i = 0; i < ObjectInfoList_length; i++)
			{
				this.ObjectInfoList[i] = new ObjectItemToSell();
				this.ObjectInfoList[i].Deserialize(reader);
			}

		}


	}
}
