//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:52.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.exchanges
{
	public class ExchangePlayerRequestMessage : ExchangeRequestMessage, IDofusMessage
	{
		public new const int NetworkId = 5773;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> Target { get; set; }


		public ExchangePlayerRequestMessage() { }


		public ExchangePlayerRequestMessage InitExchangePlayerRequestMessage(CustomVar<long> _target)
		{

			this.Target = _target;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Target);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Target);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Target = reader.Read<CustomVar<long>>();

		}


	}
}
