//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:59.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.presets
{
	public class SimpleCharacterCharacteristicForPreset : IDofusType
	{
		public  const int NetworkId = 541;
		public  int ProtocolId { get { return NetworkId; } }

		public string Keyword { get; set; }

		public CustomVar<short> Base { get; set; }

		public CustomVar<short> Additionnal { get; set; }


		public SimpleCharacterCharacteristicForPreset() { }


		public SimpleCharacterCharacteristicForPreset InitSimpleCharacterCharacteristicForPreset(string _keyword, CustomVar<short> _base, CustomVar<short> _additionnal)
		{

			this.Keyword = _keyword;
			this.Base = _base;
			this.Additionnal = _additionnal;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Keyword);
			size += DofusBinaryFactory.Sizing.SizeOf(Base);
			size += DofusBinaryFactory.Sizing.SizeOf(Additionnal);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Keyword);
			writer.WriteData(this.Base);
			writer.WriteData(this.Additionnal);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Keyword = reader.Read<string>();
			this.Base = reader.Read<CustomVar<short>>();
			this.Additionnal = reader.Read<CustomVar<short>>();

		}


	}
}
