//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.fight
{
	public class ProtectedEntityWaitingForHelpInfo : IDofusType
	{
		public  const int NetworkId = 186;
		public  int ProtocolId { get { return NetworkId; } }

		public int TimeLeftBeforeFight { get; set; }

		public int WaitTimeForPlacement { get; set; }

		public byte NbPositionForDefensors { get; set; }


		public ProtectedEntityWaitingForHelpInfo() { }


		public ProtectedEntityWaitingForHelpInfo InitProtectedEntityWaitingForHelpInfo(int _timeleftbeforefight, int _waittimeforplacement, byte _nbpositionfordefensors)
		{

			this.TimeLeftBeforeFight = _timeleftbeforefight;
			this.WaitTimeForPlacement = _waittimeforplacement;
			this.NbPositionForDefensors = _nbpositionfordefensors;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.TimeLeftBeforeFight);
			writer.Write(this.WaitTimeForPlacement);
			writer.Write(this.NbPositionForDefensors);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.TimeLeftBeforeFight = reader.Read<int>();
			this.WaitTimeForPlacement = reader.Read<int>();
			this.NbPositionForDefensors = reader.Read<byte>();

		}


	}
}
