//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:23.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.havenbag
{
	public class ChangeHavenBagRoomRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6638;
		public  int ProtocolId { get { return NetworkId; } }

		public byte RoomId { get; set; }


		public ChangeHavenBagRoomRequestMessage() { }


		public ChangeHavenBagRoomRequestMessage InitChangeHavenBagRoomRequestMessage(byte _roomid)
		{

			this.RoomId = _roomid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.RoomId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.RoomId = reader.Read<byte>();

		}


	}
}
