//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:54.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.guild;

namespace Renaissance.Protocol.messages.game.context.roleplay.havenbag
{
	public class HavenBagFurnituresMessage : IDofusMessage
	{
		public  const int NetworkId = 6634;
		public  int ProtocolId { get { return NetworkId; } }

		public HavenBagFurnitureInformation[] FurnituresInfos { get; set; }


		public HavenBagFurnituresMessage() { }


		public HavenBagFurnituresMessage InitHavenBagFurnituresMessage(HavenBagFurnitureInformation[] _furnituresinfos)
		{

			this.FurnituresInfos = _furnituresinfos;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.FurnituresInfos.Length));
			var memory1 = new Memory<byte>[FurnituresInfos.Length];
			for(int i = 0; i < FurnituresInfos.Length; i++)
			{
				memory1[i] = this.FurnituresInfos[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.FurnituresInfos.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int FurnituresInfos_length = reader.Read<short>();
			this.FurnituresInfos = new HavenBagFurnitureInformation[FurnituresInfos_length];
			for(int i = 0; i < FurnituresInfos_length; i++)
			{
				this.FurnituresInfos[i] = new HavenBagFurnitureInformation();
				this.FurnituresInfos[i].Deserialize(reader);
			}

		}


	}
}
