//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:24.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.havenbag
{
	public class KickHavenBagRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6652;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> GuestId { get; set; }


		public KickHavenBagRequestMessage() { }


		public KickHavenBagRequestMessage InitKickHavenBagRequestMessage(CustomVar<long> _guestid)
		{

			this.GuestId = _guestid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.GuestId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.GuestId = reader.Read<CustomVar<long>>();

		}


	}
}
