//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.character.characteristic;

namespace Renaissance.Protocol.messages.game.character.stats
{
	public class CharacterStatsListMessage : IDofusMessage
	{
		public  const int NetworkId = 500;
		public  int ProtocolId { get { return NetworkId; } }

		public CharacterCharacteristicsInformations Stats { get; set; }


		public CharacterStatsListMessage() { }


		public CharacterStatsListMessage InitCharacterStatsListMessage(CharacterCharacteristicsInformations _stats)
		{

			this.Stats = _stats;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Stats.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Stats = new CharacterCharacteristicsInformations();
			this.Stats.Deserialize(reader);

		}


	}
}
