//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.character.stats
{
	public class CharacterLevelUpMessage : IDofusMessage
	{
		public  const int NetworkId = 5670;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> NewLevel { get; set; }


		public CharacterLevelUpMessage() { }


		public CharacterLevelUpMessage InitCharacterLevelUpMessage(CustomVar<short> _newlevel)
		{

			this.NewLevel = _newlevel;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.NewLevel);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.NewLevel = reader.Read<CustomVar<short>>();

		}


	}
}
