//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.guild
{
	public class GuildEmblem : IDofusType
	{
		public  const int NetworkId = 87;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> SymbolShape { get; set; }

		public int SymbolColor { get; set; }

		public byte BackgroundShape { get; set; }

		public int BackgroundColor { get; set; }


		public GuildEmblem() { }


		public GuildEmblem InitGuildEmblem(CustomVar<short> _symbolshape, int _symbolcolor, byte _backgroundshape, int _backgroundcolor)
		{

			this.SymbolShape = _symbolshape;
			this.SymbolColor = _symbolcolor;
			this.BackgroundShape = _backgroundshape;
			this.BackgroundColor = _backgroundcolor;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.SymbolShape);
			writer.Write(this.SymbolColor);
			writer.Write(this.BackgroundShape);
			writer.Write(this.BackgroundColor);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SymbolShape = reader.Read<CustomVar<short>>();
			this.SymbolColor = reader.Read<int>();
			this.BackgroundShape = reader.Read<byte>();
			this.BackgroundColor = reader.Read<int>();

		}


	}
}
