//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class SoundAnimation
{

    public uint Id { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public string Filename { get; set; }

    public int Volume { get; set; }

    public int Rolloff { get; set; }

    public int AutomationDuration { get; set; }

    public int AutomationVolume { get; set; }

    public int AutomationFadeIn { get; set; }

    public int AutomationFadeOut { get; set; }

    public bool NoCutSilence { get; set; }

    public uint StartFrame { get; set; }

}