//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:32.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.roleplay.alignment.war.effort
{
	public class AlignmentWarEffortInformation : IDofusType
	{
		public  const int NetworkId = 571;
		public  int ProtocolId { get { return NetworkId; } }

		public byte AlignmentSide { get; set; }

		public CustomVar<long> AlignmentWarEffort { get; set; }


		public AlignmentWarEffortInformation() { }


		public AlignmentWarEffortInformation InitAlignmentWarEffortInformation(byte _alignmentside, CustomVar<long> _alignmentwareffort)
		{

			this.AlignmentSide = _alignmentside;
			this.AlignmentWarEffort = _alignmentwareffort;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.AlignmentSide);
			writer.Write(this.AlignmentWarEffort);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.AlignmentSide = reader.Read<byte>();
			this.AlignmentWarEffort = reader.Read<CustomVar<long>>();

		}


	}
}
