//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:57.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.character
{
	public class CharacterMinimalGuildPublicInformations : CharacterMinimalInformations, IDofusType
	{
		public new const int NetworkId = 556;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> Rank { get; set; }


		public CharacterMinimalGuildPublicInformations() { }


		public CharacterMinimalGuildPublicInformations InitCharacterMinimalGuildPublicInformations(CustomVar<int> _rank)
		{

			this.Rank = _rank;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Rank);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Rank);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Rank = reader.Read<CustomVar<int>>();

		}


	}
}
