//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:54.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.job
{
	public class JobCrafterDirectoryListRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6047;
		public  int ProtocolId { get { return NetworkId; } }

		public byte JobId { get; set; }


		public JobCrafterDirectoryListRequestMessage() { }


		public JobCrafterDirectoryListRequestMessage InitJobCrafterDirectoryListRequestMessage(byte _jobid)
		{

			this.JobId = _jobid;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(JobId);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.JobId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.JobId = reader.Read<byte>();

		}


	}
}
