//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:54.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.job;

namespace Renaissance.Protocol.messages.game.context.roleplay.job
{
	public class JobCrafterDirectoryAddMessage : IDofusMessage
	{
		public  const int NetworkId = 5651;
		public  int ProtocolId { get { return NetworkId; } }

		public JobCrafterDirectoryListEntry ListEntry { get; set; }


		public JobCrafterDirectoryAddMessage() { }


		public JobCrafterDirectoryAddMessage InitJobCrafterDirectoryAddMessage(JobCrafterDirectoryListEntry _listentry)
		{

			this.ListEntry = _listentry;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.ListEntry.Serialize();
			size += serialized1.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ListEntry = new JobCrafterDirectoryListEntry();
			this.ListEntry.Deserialize(reader);

		}


	}
}
