//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.job;

namespace Renaissance.Protocol.messages.game.context.roleplay.job
{
	public class JobDescriptionMessage : IDofusMessage
	{
		public  const int NetworkId = 5655;
		public  int ProtocolId { get { return NetworkId; } }

		public JobDescription[] JobsDescription { get; set; }


		public JobDescriptionMessage() { }


		public JobDescriptionMessage InitJobDescriptionMessage(JobDescription[] _jobsdescription)
		{

			this.JobsDescription = _jobsdescription;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.JobsDescription.Length));
			var memory1 = new Memory<byte>[JobsDescription.Length];
			for(int i = 0; i < JobsDescription.Length; i++)
			{
				memory1[i] = this.JobsDescription[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.JobsDescription.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int JobsDescription_length = reader.Read<short>();
			this.JobsDescription = new JobDescription[JobsDescription_length];
			for(int i = 0; i < JobsDescription_length; i++)
			{
				this.JobsDescription[i] = new JobDescription();
				this.JobsDescription[i].Deserialize(reader);
			}

		}


	}
}
