//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:24.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.job;

namespace Renaissance.Protocol.messages.game.context.roleplay.job
{
	public class JobExperienceMultiUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 5809;
		public  int ProtocolId { get { return NetworkId; } }

		public JobExperience[] ExperiencesUpdate { get; set; }


		public JobExperienceMultiUpdateMessage() { }


		public JobExperienceMultiUpdateMessage InitJobExperienceMultiUpdateMessage(JobExperience[] _experiencesupdate)
		{

			this.ExperiencesUpdate = _experiencesupdate;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.ExperiencesUpdate.Length));
			foreach(var obj in ExperiencesUpdate)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int ExperiencesUpdate_length = reader.Read<short>();
			this.ExperiencesUpdate = new JobExperience[ExperiencesUpdate_length];
			for(int i = 0; i < ExperiencesUpdate_length; i++)
			{
				this.ExperiencesUpdate[i] = new JobExperience();
				this.ExperiencesUpdate[i].Deserialize(reader);
			}

		}


	}
}
