//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:55.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay.job;

namespace Renaissance.Protocol.messages.game.context.roleplay.job
{
	public class JobExperienceMultiUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 5809;
		public  int ProtocolId { get { return NetworkId; } }

		public JobExperience[] ExperiencesUpdate { get; set; }


		public JobExperienceMultiUpdateMessage() { }


		public JobExperienceMultiUpdateMessage InitJobExperienceMultiUpdateMessage(JobExperience[] _experiencesupdate)
		{

			this.ExperiencesUpdate = _experiencesupdate;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.ExperiencesUpdate.Length));
			var memory1 = new Memory<byte>[ExperiencesUpdate.Length];
			for(int i = 0; i < ExperiencesUpdate.Length; i++)
			{
				memory1[i] = this.ExperiencesUpdate[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.ExperiencesUpdate.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int ExperiencesUpdate_length = reader.Read<short>();
			this.ExperiencesUpdate = new JobExperience[ExperiencesUpdate_length];
			for(int i = 0; i < ExperiencesUpdate_length; i++)
			{
				this.ExperiencesUpdate[i] = new JobExperience();
				this.ExperiencesUpdate[i].Deserialize(reader);
			}

		}


	}
}
