//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:53.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.messages.game.context.roleplay;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.context.roleplay;
using    Renaissance.Protocol.types.game.house;
using    Renaissance.Protocol.types.game.interactive;
using    Renaissance.Protocol.types.game.interactive;
using    Renaissance.Protocol.types.game.interactive;

namespace Renaissance.Protocol.messages.game.context.roleplay.anomaly
{
	public class MapComplementaryInformationsAnomalyMessage : MapComplementaryInformationsDataMessage, IDofusMessage
	{
		public new const int NetworkId = 6828;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Level { get; set; }

		public CustomVar<long> ClosingTime { get; set; }


		public MapComplementaryInformationsAnomalyMessage() { }


		public MapComplementaryInformationsAnomalyMessage InitMapComplementaryInformationsAnomalyMessage(CustomVar<short> _subareaid, double _mapid, HouseInformations[] _houses, GameRolePlayActorInformations[] _actors, InteractiveElement[] _interactiveelements, StatedElement[] _statedelements, MapObstacle[] _obstacles, FightCommonInformations[] _fights, bool _hasaggressivemonsters, FightStartingPositions _fightstartpositions, CustomVar<short> _level, CustomVar<long> _closingtime)
		{

			base.SubAreaId = _subareaid;
			base.MapId = _mapid;
			base.Houses = _houses;
			base.Actors = _actors;
			base.InteractiveElements = _interactiveelements;
			base.StatedElements = _statedelements;
			base.Obstacles = _obstacles;
			base.Fights = _fights;
			base.HasAggressiveMonsters = _hasaggressivemonsters;
			base.FightStartPositions = _fightstartpositions;
			this.Level = _level;
			this.ClosingTime = _closingtime;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Level);
			size += DofusBinaryFactory.Sizing.SizeOf(ClosingTime);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Level);
			writer.WriteData(this.ClosingTime);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Level = reader.Read<CustomVar<short>>();
			this.ClosingTime = reader.Read<CustomVar<long>>();

		}


	}
}
