//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:29.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class FightCommonInformations : IDofusType
	{
		public  const int NetworkId = 43;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> FightId { get; set; }

		public byte FightType { get; set; }

		public FightTeamInformations[] FightTeams { get; set; }

		public CustomVar<short>[] FightTeamsPositions { get; set; }

		public FightOptionsInformations[] FightTeamsOptions { get; set; }


		public FightCommonInformations() { }


		public FightCommonInformations InitFightCommonInformations(CustomVar<short> _fightid, byte _fighttype, FightTeamInformations[] _fightteams, CustomVar<short>[] _fightteamspositions, FightOptionsInformations[] _fightteamsoptions)
		{

			this.FightId = _fightid;
			this.FightType = _fighttype;
			this.FightTeams = _fightteams;
			this.FightTeamsPositions = _fightteamspositions;
			this.FightTeamsOptions = _fightteamsoptions;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.FightId);
			writer.Write(this.FightType);
			writer.Write((short)(this.FightTeams.Length));
			foreach(var obj in FightTeams)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}
			writer.Write((short)(this.FightTeamsPositions.Length));
			foreach(var item in FightTeamsPositions)
				writer.Write(item);
			writer.Write((short)(this.FightTeamsOptions.Length));
			foreach(var obj in FightTeamsOptions)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.FightId = reader.Read<CustomVar<short>>();
			this.FightType = reader.Read<byte>();
			int FightTeams_length = reader.Read<short>();
			this.FightTeams = new FightTeamInformations[FightTeams_length];
			for(int i = 0; i < FightTeams_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.FightTeams[i] = new FightTeamInformations();
				this.FightTeams[i].Deserialize(reader);
			}
			int FightTeamsPositions_length = reader.Read<short>();
			this.FightTeamsPositions = new CustomVar<short>[FightTeamsPositions_length];
			for(int i = 0; i < FightTeamsPositions_length; i++)
				this.FightTeamsPositions[i] = reader.Read<CustomVar<short>>();
			int FightTeamsOptions_length = reader.Read<short>();
			this.FightTeamsOptions = new FightOptionsInformations[FightTeamsOptions_length];
			for(int i = 0; i < FightTeamsOptions_length; i++)
			{
				this.FightTeamsOptions[i] = new FightOptionsInformations();
				this.FightTeamsOptions[i].Deserialize(reader);
			}

		}


	}
}
