//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:29.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class FightTeamMemberWithAllianceCharacterInformations : FightTeamMemberCharacterInformations, IDofusType
	{
		public new const int NetworkId = 426;
		public new int ProtocolId { get { return NetworkId; } }

		public BasicAllianceInformations AllianceInfos { get; set; }


		public FightTeamMemberWithAllianceCharacterInformations() { }


		public FightTeamMemberWithAllianceCharacterInformations InitFightTeamMemberWithAllianceCharacterInformations(BasicAllianceInformations _allianceinfos)
		{

			this.AllianceInfos = _allianceinfos;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.AllianceInfos.Serialize());

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.AllianceInfos = new BasicAllianceInformations();
			this.AllianceInfos.Deserialize(reader);

		}


	}
}
