//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:00.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class GameFightFighterEntityLightInformation : GameFightFighterLightInformations, IDofusType
	{
		public new const int NetworkId = 548;
		public new int ProtocolId { get { return NetworkId; } }

		public byte EntityModelId { get; set; }

		public double MasterId { get; set; }


		public GameFightFighterEntityLightInformation() { }


		public GameFightFighterEntityLightInformation InitGameFightFighterEntityLightInformation(byte _entitymodelid, double _masterid)
		{

			this.EntityModelId = _entitymodelid;
			this.MasterId = _masterid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(EntityModelId);
			size += DofusBinaryFactory.Sizing.SizeOf(MasterId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.EntityModelId);
			writer.WriteData(this.MasterId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.EntityModelId = reader.Read<byte>();
			this.MasterId = reader.Read<double>();

		}


	}
}
