//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:00.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class GameFightEffectTriggerCount : IDofusType
	{
		public  const int NetworkId = 569;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> EffectId { get; set; }

		public double TargetId { get; set; }

		public byte Count { get; set; }


		public GameFightEffectTriggerCount() { }


		public GameFightEffectTriggerCount InitGameFightEffectTriggerCount(CustomVar<int> _effectid, double _targetid, byte _count)
		{

			this.EffectId = _effectid;
			this.TargetId = _targetid;
			this.Count = _count;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(EffectId);
			size += DofusBinaryFactory.Sizing.SizeOf(TargetId);
			size += DofusBinaryFactory.Sizing.SizeOf(Count);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.EffectId);
			writer.WriteData(this.TargetId);
			writer.WriteData(this.Count);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.EffectId = reader.Read<CustomVar<int>>();
			this.TargetId = reader.Read<double>();
			this.Count = reader.Read<byte>();

		}


	}
}
