//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:30.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class GameFightMinimalStatsPreparation : GameFightMinimalStats, IDofusType
	{
		public new const int NetworkId = 360;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> Initiative { get; set; }


		public GameFightMinimalStatsPreparation() { }


		public GameFightMinimalStatsPreparation InitGameFightMinimalStatsPreparation(CustomVar<int> _initiative)
		{

			this.Initiative = _initiative;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Initiative);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Initiative = reader.Read<CustomVar<int>>();

		}


	}
}
