//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:00.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.fight
{
	public class SpawnMonsterInformation : SpawnInformation, IDofusType
	{
		public new const int NetworkId = 572;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> CreatureGenericId { get; set; }

		public byte CreatureGrade { get; set; }


		public SpawnMonsterInformation() { }


		public SpawnMonsterInformation InitSpawnMonsterInformation(CustomVar<short> _creaturegenericid, byte _creaturegrade)
		{

			this.CreatureGenericId = _creaturegenericid;
			this.CreatureGrade = _creaturegrade;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(CreatureGenericId);
			size += DofusBinaryFactory.Sizing.SizeOf(CreatureGrade);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.CreatureGenericId);
			writer.WriteData(this.CreatureGrade);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.CreatureGenericId = reader.Read<CustomVar<short>>();
			this.CreatureGrade = reader.Read<byte>();

		}


	}
}
