//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:29.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.character.status
{
	public class PlayerStatusExtended : PlayerStatus, IDofusType
	{
		public new const int NetworkId = 414;
		public new int ProtocolId { get { return NetworkId; } }

		public string Message { get; set; }


		public PlayerStatusExtended() { }


		public PlayerStatusExtended InitPlayerStatusExtended(string _message)
		{

			this.Message = _message;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Message);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Message = reader.Read<string>();

		}


	}
}
