//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightPlacementSwapPositionsCancelledMessage : IDofusMessage
	{
		public  const int NetworkId = 6546;
		public  int ProtocolId { get { return NetworkId; } }

		public int RequestId { get; set; }

		public double CancellerId { get; set; }


		public GameFightPlacementSwapPositionsCancelledMessage() { }


		public GameFightPlacementSwapPositionsCancelledMessage InitGameFightPlacementSwapPositionsCancelledMessage(int _requestid, double _cancellerid)
		{

			this.RequestId = _requestid;
			this.CancellerId = _cancellerid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.RequestId);
			writer.Write(this.CancellerId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.RequestId = reader.Read<int>();
			this.CancellerId = reader.Read<double>();

		}


	}
}
