//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using Renaissance.Binary;
using Renaissance.Protocol.types.game.context.fight;

namespace Renaissance.Protocol.messages.game.context.fight
{
    public class GameFightResumeMessage : GameFightSpectateMessage, IDofusMessage
	{
		public new const int NetworkId = 6067;
		public new int ProtocolId { get { return NetworkId; } }

		public GameFightSpellCooldown[] SpellCooldowns { get; set; }

		public byte SummonCount { get; set; }

		public byte BombCount { get; set; }


		public GameFightResumeMessage() { }


		public GameFightResumeMessage InitGameFightResumeMessage(GameFightSpellCooldown[] _spellcooldowns, byte _summoncount, byte _bombcount)
		{

			this.SpellCooldowns = _spellcooldowns;
			this.SummonCount = _summoncount;
			this.BombCount = _bombcount;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write((short)(this.SpellCooldowns.Length));
			foreach(var obj in SpellCooldowns)
			{
				writer.Write(obj.Serialize());
			}
			writer.Write(this.SummonCount);
			writer.Write(this.BombCount);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			int SpellCooldowns_length = reader.Read<short>();
			this.SpellCooldowns = new GameFightSpellCooldown[SpellCooldowns_length];
			for(int i = 0; i < SpellCooldowns_length; i++)
			{
				this.SpellCooldowns[i] = new GameFightSpellCooldown();
				this.SpellCooldowns[i].Deserialize(reader);
			}
			this.SummonCount = reader.Read<byte>();
			this.BombCount = reader.Read<byte>();

		}


	}
}
