//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:49.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.action.fight;
using    Renaissance.Protocol.types.game.actions.fight;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.idol;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightResumeMessage : GameFightSpectateMessage, IDofusMessage
	{
		public new const int NetworkId = 6067;
		public new int ProtocolId { get { return NetworkId; } }

		public GameFightSpellCooldown[] SpellCooldowns { get; set; }

		public byte SummonCount { get; set; }

		public byte BombCount { get; set; }


		public GameFightResumeMessage() { }


		public GameFightResumeMessage InitGameFightResumeMessage(GameFightSpellCooldown[] _spellcooldowns, byte _summoncount, byte _bombcount)
		{

			this.SpellCooldowns = _spellcooldowns;
			this.SummonCount = _summoncount;
			this.BombCount = _bombcount;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.SpellCooldowns.Length));
			var memory1 = new Memory<byte>[SpellCooldowns.Length];
			for(int i = 0; i < SpellCooldowns.Length; i++)
			{
				memory1[i] = this.SpellCooldowns[i].Serialize();
				size += memory1[i].Length;
			}
			size += DofusBinaryFactory.Sizing.SizeOf(SummonCount);
			size += DofusBinaryFactory.Sizing.SizeOf(BombCount);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData((short)(this.SpellCooldowns.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}
			writer.WriteData(this.SummonCount);
			writer.WriteData(this.BombCount);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			int SpellCooldowns_length = reader.Read<short>();
			this.SpellCooldowns = new GameFightSpellCooldown[SpellCooldowns_length];
			for(int i = 0; i < SpellCooldowns_length; i++)
			{
				this.SpellCooldowns[i] = new GameFightSpellCooldown();
				this.SpellCooldowns[i].Deserialize(reader);
			}
			this.SummonCount = reader.Read<byte>();
			this.BombCount = reader.Read<byte>();

		}


	}
}
