//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:49.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightTurnStartMessage : IDofusMessage
	{
		public  const int NetworkId = 714;
		public  int ProtocolId { get { return NetworkId; } }

		public double Id { get; set; }

		public CustomVar<int> WaitTime { get; set; }


		public GameFightTurnStartMessage() { }


		public GameFightTurnStartMessage InitGameFightTurnStartMessage(double _id, CustomVar<int> _waittime)
		{

			this.Id = _id;
			this.WaitTime = _waittime;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Id);
			size += DofusBinaryFactory.Sizing.SizeOf(WaitTime);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Id);
			writer.WriteData(this.WaitTime);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Id = reader.Read<double>();
			this.WaitTime = reader.Read<CustomVar<int>>();

		}


	}
}
