//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:18.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightTurnFinishMessage : IDofusMessage
	{
		public  const int NetworkId = 718;
		public  int ProtocolId { get { return NetworkId; } }

		public bool IsAfk { get; set; }


		public GameFightTurnFinishMessage() { }


		public GameFightTurnFinishMessage InitGameFightTurnFinishMessage(bool _isafk)
		{

			this.IsAfk = _isafk;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.IsAfk);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.IsAfk = reader.Read<bool>();

		}


	}
}
