//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightOptionToggleMessage : IDofusMessage
	{
		public  const int NetworkId = 707;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Option { get; set; }


		public GameFightOptionToggleMessage() { }


		public GameFightOptionToggleMessage InitGameFightOptionToggleMessage(byte _option)
		{

			this.Option = _option;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Option);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Option = reader.Read<byte>();

		}


	}
}
