//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:49.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight
{
	public class GameFightTurnListMessage : IDofusMessage
	{
		public  const int NetworkId = 713;
		public  int ProtocolId { get { return NetworkId; } }

		public double[] Ids { get; set; }

		public double[] DeadsIds { get; set; }


		public GameFightTurnListMessage() { }


		public GameFightTurnListMessage InitGameFightTurnListMessage(double[] _ids, double[] _deadsids)
		{

			this.Ids = _ids;
			this.DeadsIds = _deadsids;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.Ids.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(Ids);
			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.DeadsIds.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(DeadsIds);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.Ids.Length));
			writer.WriteDatas(Ids);
			writer.WriteData((short)(this.DeadsIds.Length));
			writer.WriteDatas(DeadsIds);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Ids_length = reader.Read<short>();
			this.Ids = new double[Ids_length];
			for(int i = 0; i < Ids_length; i++)
				this.Ids[i] = reader.Read<double>();
			int DeadsIds_length = reader.Read<short>();
			this.DeadsIds = new double[DeadsIds_length];
			for(int i = 0; i < DeadsIds_length; i++)
				this.DeadsIds[i] = reader.Read<double>();

		}


	}
}
