//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.interactive
{
	public class InteractiveElementWithAgeBonus : InteractiveElement, IDofusType
	{
		public new const int NetworkId = 398;
		public new int ProtocolId { get { return NetworkId; } }

		public short AgeBonus { get; set; }


		public InteractiveElementWithAgeBonus() { }


		public InteractiveElementWithAgeBonus InitInteractiveElementWithAgeBonus(short _agebonus)
		{

			this.AgeBonus = _agebonus;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.AgeBonus);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.AgeBonus = reader.Read<short>();

		}


	}
}
