//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:01.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.roleplay.job
{
	public class JobCrafterDirectoryEntryJobInfo : IDofusType
	{
		public  const int NetworkId = 195;
		public  int ProtocolId { get { return NetworkId; } }

		public byte JobId { get; set; }

		public byte JobLevel { get; set; }

		public bool Free { get; set; }

		public byte MinLevel { get; set; }


		public JobCrafterDirectoryEntryJobInfo() { }


		public JobCrafterDirectoryEntryJobInfo InitJobCrafterDirectoryEntryJobInfo(byte _jobid, byte _joblevel, bool _free, byte _minlevel)
		{

			this.JobId = _jobid;
			this.JobLevel = _joblevel;
			this.Free = _free;
			this.MinLevel = _minlevel;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(JobId);
			size += DofusBinaryFactory.Sizing.SizeOf(JobLevel);
			size += DofusBinaryFactory.Sizing.SizeOf(Free);
			size += DofusBinaryFactory.Sizing.SizeOf(MinLevel);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.JobId);
			writer.WriteData(this.JobLevel);
			writer.WriteData(this.Free);
			writer.WriteData(this.MinLevel);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.JobId = reader.Read<byte>();
			this.JobLevel = reader.Read<byte>();
			this.Free = reader.Read<bool>();
			this.MinLevel = reader.Read<byte>();

		}


	}
}
