//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:31.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.interactive.skill;

namespace Renaissance.Protocol.types.game.context.roleplay.job
{
	public class JobDescription : IDofusType
	{
		public  const int NetworkId = 101;
		public  int ProtocolId { get { return NetworkId; } }

		public byte JobId { get; set; }

		public SkillActionDescription[] Skills { get; set; }


		public JobDescription() { }


		public JobDescription InitJobDescription(byte _jobid, SkillActionDescription[] _skills)
		{

			this.JobId = _jobid;
			this.Skills = _skills;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.JobId);
			writer.Write((short)(this.Skills.Length));
			foreach(var obj in Skills)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.JobId = reader.Read<byte>();
			int Skills_length = reader.Read<short>();
			this.Skills = new SkillActionDescription[Skills_length];
			for(int i = 0; i < Skills_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.Skills[i] = new SkillActionDescription();
				this.Skills[i].Deserialize(reader);
			}

		}


	}
}
