//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:13.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.presets
{
	public class PresetDeleteRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6755;
		public  int ProtocolId { get { return NetworkId; } }

		public short PresetId { get; set; }


		public PresetDeleteRequestMessage() { }


		public PresetDeleteRequestMessage InitPresetDeleteRequestMessage(short _presetid)
		{

			this.PresetId = _presetid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.PresetId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.PresetId = reader.Read<short>();

		}


	}
}
