//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:10.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context;

namespace Renaissance.Protocol.messages.game.context
{
	public class GameMapChangeOrientationsMessage : IDofusMessage
	{
		public  const int NetworkId = 6155;
		public  int ProtocolId { get { return NetworkId; } }

		public ActorOrientation[] Orientations { get; set; }


		public GameMapChangeOrientationsMessage() { }


		public GameMapChangeOrientationsMessage InitGameMapChangeOrientationsMessage(ActorOrientation[] _orientations)
		{

			this.Orientations = _orientations;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Orientations.Length));
			foreach(var obj in Orientations)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Orientations_length = reader.Read<short>();
			this.Orientations = new ActorOrientation[Orientations_length];
			for(int i = 0; i < Orientations_length; i++)
			{
				this.Orientations[i] = new ActorOrientation();
				this.Orientations[i].Deserialize(reader);
			}

		}


	}
}
