//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:10.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context
{
	public class GameContextReadyMessage : IDofusMessage
	{
		public  const int NetworkId = 6071;
		public  int ProtocolId { get { return NetworkId; } }

		public double MapId { get; set; }


		public GameContextReadyMessage() { }


		public GameContextReadyMessage InitGameContextReadyMessage(double _mapid)
		{

			this.MapId = _mapid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.MapId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MapId = reader.Read<double>();

		}


	}
}
