//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:10.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context
{
	public class GameMapChangeOrientationRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 945;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Direction { get; set; }


		public GameMapChangeOrientationRequestMessage() { }


		public GameMapChangeOrientationRequestMessage InitGameMapChangeOrientationRequestMessage(byte _direction)
		{

			this.Direction = _direction;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Direction);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Direction = reader.Read<byte>();

		}


	}
}
