//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:44.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context
{
	public class GameMapChangeOrientationRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 945;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Direction { get; set; }


		public GameMapChangeOrientationRequestMessage() { }


		public GameMapChangeOrientationRequestMessage InitGameMapChangeOrientationRequestMessage(byte _direction)
		{

			this.Direction = _direction;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Direction);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Direction);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Direction = reader.Read<byte>();

		}


	}
}
