//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:44.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context
{
	public class ShowCellMessage : IDofusMessage
	{
		public  const int NetworkId = 5612;
		public  int ProtocolId { get { return NetworkId; } }

		public double SourceId { get; set; }

		public CustomVar<short> CellId { get; set; }


		public ShowCellMessage() { }


		public ShowCellMessage InitShowCellMessage(double _sourceid, CustomVar<short> _cellid)
		{

			this.SourceId = _sourceid;
			this.CellId = _cellid;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(SourceId);
			size += DofusBinaryFactory.Sizing.SizeOf(CellId);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.SourceId);
			writer.WriteData(this.CellId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SourceId = reader.Read<double>();
			this.CellId = reader.Read<CustomVar<short>>();

		}


	}
}
