//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:07.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.connection
{
	public class MigratedServerListMessage : IDofusMessage
	{
		public  const int NetworkId = 6731;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short>[] MigratedServerIds { get; set; }


		public MigratedServerListMessage() { }


		public MigratedServerListMessage InitMigratedServerListMessage(CustomVar<short>[] _migratedserverids)
		{

			this.MigratedServerIds = _migratedserverids;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.MigratedServerIds.Length));
			foreach(var item in MigratedServerIds)
				writer.Write(item);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int MigratedServerIds_length = reader.Read<short>();
			this.MigratedServerIds = new CustomVar<short>[MigratedServerIds_length];
			for(int i = 0; i < MigratedServerIds_length; i++)
				this.MigratedServerIds[i] = reader.Read<CustomVar<short>>();

		}


	}
}
