//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:16.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.character.choice
{
	public class CharacterFirstSelectionMessage : CharacterSelectionMessage, IDofusMessage
	{
		public new const int NetworkId = 6084;
		public new int ProtocolId { get { return NetworkId; } }

		public bool DoTutorial { get; set; }


		public CharacterFirstSelectionMessage() { }


		public CharacterFirstSelectionMessage InitCharacterFirstSelectionMessage(bool _dotutorial)
		{

			this.DoTutorial = _dotutorial;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.DoTutorial);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.DoTutorial = reader.Read<bool>();

		}


	}
}
