//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:48.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.character.choice
{
	public class CharacterFirstSelectionMessage : CharacterSelectionMessage, IDofusMessage
	{
		public new const int NetworkId = 6084;
		public new int ProtocolId { get { return NetworkId; } }

		public bool DoTutorial { get; set; }


		public CharacterFirstSelectionMessage() { }


		public CharacterFirstSelectionMessage InitCharacterFirstSelectionMessage(bool _dotutorial)
		{

			this.DoTutorial = _dotutorial;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(DoTutorial);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.DoTutorial);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.DoTutorial = reader.Read<bool>();

		}


	}
}
