//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:23.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.breach
{
	public class BreachTeleportResponseMessage : IDofusMessage
	{
		public  const int NetworkId = 6816;
		public  int ProtocolId { get { return NetworkId; } }

		public bool Teleported { get; set; }


		public BreachTeleportResponseMessage() { }


		public BreachTeleportResponseMessage InitBreachTeleportResponseMessage(bool _teleported)
		{

			this.Teleported = _teleported;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Teleported);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Teleported = reader.Read<bool>();

		}


	}
}
