//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:08.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.connection.search
{
	public class AcquaintanceSearchMessage : IDofusMessage
	{
		public  const int NetworkId = 6144;
		public  int ProtocolId { get { return NetworkId; } }

		public string Nickname { get; set; }


		public AcquaintanceSearchMessage() { }


		public AcquaintanceSearchMessage InitAcquaintanceSearchMessage(string _nickname)
		{

			this.Nickname = _nickname;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Nickname);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Nickname = reader.Read<string>();

		}


	}
}
