//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:29.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.guild;

namespace Renaissance.Protocol.types.game.social
{
	public class GuildInsiderFactSheetInformations : GuildFactSheetInformations, IDofusType
	{
		public new const int NetworkId = 423;
		public new int ProtocolId { get { return NetworkId; } }

		public string LeaderName { get; set; }

		public CustomVar<short> NbConnectedMembers { get; set; }

		public byte NbTaxCollectors { get; set; }

		public int LastActivity { get; set; }


		public GuildInsiderFactSheetInformations() { }


		public GuildInsiderFactSheetInformations InitGuildInsiderFactSheetInformations(string _leadername, CustomVar<short> _nbconnectedmembers, byte _nbtaxcollectors, int _lastactivity)
		{

			this.LeaderName = _leadername;
			this.NbConnectedMembers = _nbconnectedmembers;
			this.NbTaxCollectors = _nbtaxcollectors;
			this.LastActivity = _lastactivity;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.LeaderName);
			writer.Write(this.NbConnectedMembers);
			writer.Write(this.NbTaxCollectors);
			writer.Write(this.LastActivity);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.LeaderName = reader.Read<string>();
			this.NbConnectedMembers = reader.Read<CustomVar<short>>();
			this.NbTaxCollectors = reader.Read<byte>();
			this.LastActivity = reader.Read<int>();

		}


	}
}
