//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:26.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.treasureHunt
{
	public class TreasureHuntGiveUpRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6487;
		public  int ProtocolId { get { return NetworkId; } }

		public byte QuestType { get; set; }


		public TreasureHuntGiveUpRequestMessage() { }


		public TreasureHuntGiveUpRequestMessage InitTreasureHuntGiveUpRequestMessage(byte _questtype)
		{

			this.QuestType = _questtype;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.QuestType);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.QuestType = reader.Read<byte>();

		}


	}
}
