//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:41.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.handshake
{
	public class ProtocolRequired : IDofusMessage
	{
		public  const int NetworkId = 1;
		public  int ProtocolId { get { return NetworkId; } }

		public int RequiredVersion { get; set; }

		public int CurrentVersion { get; set; }


		public ProtocolRequired() { }


		public ProtocolRequired InitProtocolRequired(int _requiredversion, int _currentversion)
		{

			this.RequiredVersion = _requiredversion;
			this.CurrentVersion = _currentversion;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(RequiredVersion);
			size += DofusBinaryFactory.Sizing.SizeOf(CurrentVersion);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.RequiredVersion);
			writer.WriteData(this.CurrentVersion);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.RequiredVersion = reader.Read<int>();
			this.CurrentVersion = reader.Read<int>();

		}


	}
}
