//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:57.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.approach
{
	public class ServerSessionConstant : IDofusType
	{
		public  const int NetworkId = 430;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Id { get; set; }


		public ServerSessionConstant() { }


		public ServerSessionConstant InitServerSessionConstant(CustomVar<short> _id)
		{

			this.Id = _id;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Id);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Id);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Id = reader.Read<CustomVar<short>>();

		}


	}
}
