//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:45.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildMemberOnlineStatusMessage : IDofusMessage
	{
		public  const int NetworkId = 6061;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> MemberId { get; set; }

		public bool Online { get; set; }


		public GuildMemberOnlineStatusMessage() { }


		public GuildMemberOnlineStatusMessage InitGuildMemberOnlineStatusMessage(CustomVar<long> _memberid, bool _online)
		{

			this.MemberId = _memberid;
			this.Online = _online;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(MemberId);
			size += DofusBinaryFactory.Sizing.SizeOf(Online);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.MemberId);
			writer.WriteData(this.Online);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MemberId = reader.Read<CustomVar<long>>();
			this.Online = reader.Read<bool>();

		}


	}
}
