//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:12.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildPaddockRemovedMessage : IDofusMessage
	{
		public  const int NetworkId = 5955;
		public  int ProtocolId { get { return NetworkId; } }

		public double PaddockId { get; set; }


		public GuildPaddockRemovedMessage() { }


		public GuildPaddockRemovedMessage InitGuildPaddockRemovedMessage(double _paddockid)
		{

			this.PaddockId = _paddockid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.PaddockId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.PaddockId = reader.Read<double>();

		}


	}
}
