//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:45.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildInvitationStateRecrutedMessage : IDofusMessage
	{
		public  const int NetworkId = 5548;
		public  int ProtocolId { get { return NetworkId; } }

		public byte InvitationState { get; set; }


		public GuildInvitationStateRecrutedMessage() { }


		public GuildInvitationStateRecrutedMessage InitGuildInvitationStateRecrutedMessage(byte _invitationstate)
		{

			this.InvitationState = _invitationstate;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(InvitationState);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.InvitationState);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.InvitationState = reader.Read<byte>();

		}


	}
}
