//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:12.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.guild;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildModificationValidMessage : IDofusMessage
	{
		public  const int NetworkId = 6323;
		public  int ProtocolId { get { return NetworkId; } }

		public string GuildName { get; set; }

		public GuildEmblem GuildEmblem { get; set; }


		public GuildModificationValidMessage() { }


		public GuildModificationValidMessage InitGuildModificationValidMessage(string _guildname, GuildEmblem _guildemblem)
		{

			this.GuildName = _guildname;
			this.GuildEmblem = _guildemblem;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.GuildName);
			writer.Write(this.GuildEmblem.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.GuildName = reader.Read<string>();
			this.GuildEmblem = new GuildEmblem();
			this.GuildEmblem.Deserialize(reader);

		}


	}
}
