//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:11.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildCreationResultMessage : IDofusMessage
	{
		public  const int NetworkId = 5554;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Result { get; set; }


		public GuildCreationResultMessage() { }


		public GuildCreationResultMessage InitGuildCreationResultMessage(byte _result)
		{

			this.Result = _result;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Result);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Result = reader.Read<byte>();

		}


	}
}
