//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:11.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.messages.game.social;

namespace Renaissance.Protocol.messages.game.guild
{
	public class GuildBulletinSetRequestMessage : SocialNoticeSetRequestMessage, IDofusMessage
	{
		public new const int NetworkId = 6694;
		public new int ProtocolId { get { return NetworkId; } }

		public string Content { get; set; }

		public bool NotifyMembers { get; set; }


		public GuildBulletinSetRequestMessage() { }


		public GuildBulletinSetRequestMessage InitGuildBulletinSetRequestMessage(string _content, bool _notifymembers)
		{

			this.Content = _content;
			this.NotifyMembers = _notifymembers;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Content);
			writer.Write(this.NotifyMembers);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Content = reader.Read<string>();
			this.NotifyMembers = reader.Read<bool>();

		}


	}
}
