//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class Breed
{

    public int Id { get; set; }

    public uint ShortNameId { get; set; }

    public uint LongNameId { get; set; }

    public uint DescriptionId { get; set; }

    public uint GameplayDescriptionId { get; set; }

    public uint GameplayClassDescriptionId { get; set; }

    public string MaleLook { get; set; }

    public string FemaleLook { get; set; }

    public uint CreatureBonesId { get; set; }

    public int MaleArtwork { get; set; }

    public int FemaleArtwork { get; set; }

    public List<List<uint>> StatsPointsForStrength { get; set; }

    public List<List<uint>> StatsPointsForIntelligence { get; set; }

    public List<List<uint>> StatsPointsForChance { get; set; }

    public List<List<uint>> StatsPointsForAgility { get; set; }

    public List<List<uint>> StatsPointsForVitality { get; set; }

    public List<List<uint>> StatsPointsForWisdom { get; set; }

    public List<uint> BreedSpellsId { get; set; }

    public List<BreedRoleByBreed> BreedRoles { get; set; }

    public List<uint> MaleColors { get; set; }

    public List<uint> FemaleColors { get; set; }

    public uint SpawnMap { get; set; }

    public uint Complexity { get; set; }

    public uint SortIndex { get; set; }

}