//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:17.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.chat.smiley
{
	public class ChatSmileyRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 800;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> SmileyId { get; set; }


		public ChatSmileyRequestMessage() { }


		public ChatSmileyRequestMessage InitChatSmileyRequestMessage(CustomVar<short> _smileyid)
		{

			this.SmileyId = _smileyid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.SmileyId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SmileyId = reader.Read<CustomVar<short>>();

		}


	}
}
