//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:26.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.fight.arena
{
	public class GameRolePlayArenaSwitchToGameServerMessage : IDofusMessage
	{
		public  const int NetworkId = 6574;
		public  int ProtocolId { get { return NetworkId; } }

		public bool ValidToken { get; set; }

		public byte[] Ticket { get; set; }

		public short HomeServerId { get; set; }


		public GameRolePlayArenaSwitchToGameServerMessage() { }


		public GameRolePlayArenaSwitchToGameServerMessage InitGameRolePlayArenaSwitchToGameServerMessage(bool _validtoken, byte[] _ticket, short _homeserverid)
		{

			this.ValidToken = _validtoken;
			this.Ticket = _ticket;
			this.HomeServerId = _homeserverid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.ValidToken);
			writer.Write((CustomVar<int>)(this.Ticket.Length));
			foreach(var item in Ticket)
				writer.Write(item);
			writer.Write(this.HomeServerId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ValidToken = reader.Read<bool>();
			int Ticket_length = reader.Read<CustomVar<int>>();
			this.Ticket = new byte[Ticket_length];
			for(int i = 0; i < Ticket_length; i++)
				this.Ticket[i] = reader.Read<byte>();
			this.HomeServerId = reader.Read<short>();

		}


	}
}
