//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:44.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.dialog
{
	public class LeaveDialogMessage : IDofusMessage
	{
		public  const int NetworkId = 5502;
		public  int ProtocolId { get { return NetworkId; } }

		public byte DialogType { get; set; }


		public LeaveDialogMessage() { }


		public LeaveDialogMessage InitLeaveDialogMessage(byte _dialogtype)
		{

			this.DialogType = _dialogtype;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(DialogType);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.DialogType);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.DialogType = reader.Read<byte>();

		}


	}
}
