//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:44.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.entity;

namespace Renaissance.Protocol.messages.game.entity
{
	public class EntityInformationMessage : IDofusMessage
	{
		public  const int NetworkId = 6771;
		public  int ProtocolId { get { return NetworkId; } }

		public EntityInformation Entity { get; set; }


		public EntityInformationMessage() { }


		public EntityInformationMessage InitEntityInformationMessage(EntityInformation _entity)
		{

			this.Entity = _entity;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.Entity.Serialize();
			size += serialized1.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Entity = new EntityInformation();
			this.Entity.Deserialize(reader);

		}


	}
}
