//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:10.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.entity;

namespace Renaissance.Protocol.messages.game.entity
{
	public class EntityInformationMessage : IDofusMessage
	{
		public  const int NetworkId = 6771;
		public  int ProtocolId { get { return NetworkId; } }

		public EntityInformation Entity { get; set; }


		public EntityInformationMessage() { }


		public EntityInformationMessage InitEntityInformationMessage(EntityInformation _entity)
		{

			this.Entity = _entity;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Entity.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Entity = new EntityInformation();
			this.Entity.Deserialize(reader);

		}


	}
}
