//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:50.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay
{
	public class CurrentMapInstanceMessage : CurrentMapMessage, IDofusMessage
	{
		public new const int NetworkId = 6738;
		public new int ProtocolId { get { return NetworkId; } }

		public double InstantiatedMapId { get; set; }


		public CurrentMapInstanceMessage() { }


		public CurrentMapInstanceMessage InitCurrentMapInstanceMessage(double _instantiatedmapid)
		{

			this.InstantiatedMapId = _instantiatedmapid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(InstantiatedMapId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.InstantiatedMapId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.InstantiatedMapId = reader.Read<double>();

		}


	}
}
