//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.roleplay;

namespace Renaissance.Protocol.messages.game.context.roleplay
{
	public class GameRolePlayShowMultipleActorsMessage : IDofusMessage
	{
		public  const int NetworkId = 6712;
		public  int ProtocolId { get { return NetworkId; } }

		public GameRolePlayActorInformations[] InformationsList { get; set; }


		public GameRolePlayShowMultipleActorsMessage() { }


		public GameRolePlayShowMultipleActorsMessage InitGameRolePlayShowMultipleActorsMessage(GameRolePlayActorInformations[] _informationslist)
		{

			this.InformationsList = _informationslist;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.InformationsList.Length));
			foreach(var obj in InformationsList)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int InformationsList_length = reader.Read<short>();
			this.InformationsList = new GameRolePlayActorInformations[InformationsList_length];
			for(int i = 0; i < InformationsList_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.InformationsList[i] = new GameRolePlayActorInformations();
				this.InformationsList[i].Deserialize(reader);
			}

		}


	}
}
