//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:50.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.context.fight;
using    Renaissance.Protocol.types.game.context.roleplay;
using    Renaissance.Protocol.types.game.house;
using    Renaissance.Protocol.types.game.house;
using    Renaissance.Protocol.types.game.interactive;
using    Renaissance.Protocol.types.game.interactive;
using    Renaissance.Protocol.types.game.interactive;

namespace Renaissance.Protocol.messages.game.context.roleplay
{
	public class MapComplementaryInformationsDataInHouseMessage : MapComplementaryInformationsDataMessage, IDofusMessage
	{
		public new const int NetworkId = 6130;
		public new int ProtocolId { get { return NetworkId; } }

		public HouseInformationsInside CurrentHouse { get; set; }


		public MapComplementaryInformationsDataInHouseMessage() { }


		public MapComplementaryInformationsDataInHouseMessage InitMapComplementaryInformationsDataInHouseMessage(HouseInformationsInside _currenthouse)
		{

			this.CurrentHouse = _currenthouse;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.CurrentHouse.Serialize();
			size += serialized1.Length;
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.CurrentHouse = new HouseInformationsInside();
			this.CurrentHouse.Deserialize(reader);

		}


	}
}
