//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay
{
	public class MapFightCountMessage : IDofusMessage
	{
		public  const int NetworkId = 210;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> FightCount { get; set; }


		public MapFightCountMessage() { }


		public MapFightCountMessage InitMapFightCountMessage(CustomVar<short> _fightcount)
		{

			this.FightCount = _fightcount;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.FightCount);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.FightCount = reader.Read<CustomVar<short>>();

		}


	}
}
