//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.context.fight;

namespace Renaissance.Protocol.messages.game.context.roleplay
{
	public class MapFightStartPositionsUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 6716;
		public  int ProtocolId { get { return NetworkId; } }

		public double MapId { get; set; }

		public FightStartingPositions FightStartPositions { get; set; }


		public MapFightStartPositionsUpdateMessage() { }


		public MapFightStartPositionsUpdateMessage InitMapFightStartPositionsUpdateMessage(double _mapid, FightStartingPositions _fightstartpositions)
		{

			this.MapId = _mapid;
			this.FightStartPositions = _fightstartpositions;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.MapId);
			writer.Write(this.FightStartPositions.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MapId = reader.Read<double>();
			this.FightStartPositions = new FightStartingPositions();
			this.FightStartPositions.Deserialize(reader);

		}


	}
}
