//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:01.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.data.items
{
	public class GoldItem : Item, IDofusType
	{
		public new const int NetworkId = 123;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> Sum { get; set; }


		public GoldItem() { }


		public GoldItem InitGoldItem(CustomVar<long> _sum)
		{

			this.Sum = _sum;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Sum);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData(this.Sum);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Sum = reader.Read<CustomVar<long>>();

		}


	}
}
