//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:31.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.data.items
{
	public class ObjectItemGenericQuantity : Item, IDofusType
	{
		public new const int NetworkId = 483;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> ObjectGID { get; set; }

		public CustomVar<int> Quantity { get; set; }


		public ObjectItemGenericQuantity() { }


		public ObjectItemGenericQuantity InitObjectItemGenericQuantity(CustomVar<short> _objectgid, CustomVar<int> _quantity)
		{

			this.ObjectGID = _objectgid;
			this.Quantity = _quantity;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.ObjectGID);
			writer.Write(this.Quantity);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.ObjectGID = reader.Read<CustomVar<short>>();
			this.Quantity = reader.Read<CustomVar<int>>();

		}


	}
}
