//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.documents
{
	[D2OClass("Document", "com.ankamagames.dofus.datacenter.documents")]
	public class DocumentData : IDataCenter
	{

		private int m_id;
		private uint m_typeId;
		private Boolean m_showTitle;
		private Boolean m_showBackgroundImage;
		private uint m_titleId;
		private uint m_authorId;
		private uint m_subTitleId;
		private uint m_contentId;
		private String m_contentCSS;
		private String m_clientProperties;

		public int Id
		{
			get => m_id;
			set => m_id = value;
		}

		public uint TypeId
		{
			get => m_typeId;
			set => m_typeId = value;
		}

		public Boolean ShowTitle
		{
			get => m_showTitle;
			set => m_showTitle = value;
		}

		public Boolean ShowBackgroundImage
		{
			get => m_showBackgroundImage;
			set => m_showBackgroundImage = value;
		}

		public uint TitleId
		{
			get => m_titleId;
			set => m_titleId = value;
		}

		public uint AuthorId
		{
			get => m_authorId;
			set => m_authorId = value;
		}

		public uint SubTitleId
		{
			get => m_subTitleId;
			set => m_subTitleId = value;
		}

		public uint ContentId
		{
			get => m_contentId;
			set => m_contentId = value;
		}

		public String ContentCSS
		{
			get => m_contentCSS;
			set => m_contentCSS = value;
		}

		public String ClientProperties
		{
			get => m_clientProperties;
			set => m_clientProperties = value;
		}


	}
}
