//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:53.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class LivingObjectDissociateMessage : IDofusMessage
	{
		public  const int NetworkId = 5723;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> LivingUID { get; set; }

		public byte LivingPosition { get; set; }


		public LivingObjectDissociateMessage() { }


		public LivingObjectDissociateMessage InitLivingObjectDissociateMessage(CustomVar<int> _livinguid, byte _livingposition)
		{

			this.LivingUID = _livinguid;
			this.LivingPosition = _livingposition;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(LivingUID);
			size += DofusBinaryFactory.Sizing.SizeOf(LivingPosition);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.LivingUID);
			writer.WriteData(this.LivingPosition);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.LivingUID = reader.Read<CustomVar<int>>();
			this.LivingPosition = reader.Read<byte>();

		}


	}
}
