//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class LivingObjectMessageMessage : IDofusMessage
	{
		public  const int NetworkId = 6065;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> MsgId { get; set; }

		public int TimeStamp { get; set; }

		public string Owner { get; set; }

		public CustomVar<short> ObjectGenericId { get; set; }


		public LivingObjectMessageMessage() { }


		public LivingObjectMessageMessage InitLivingObjectMessageMessage(CustomVar<short> _msgid, int _timestamp, string _owner, CustomVar<short> _objectgenericid)
		{

			this.MsgId = _msgid;
			this.TimeStamp = _timestamp;
			this.Owner = _owner;
			this.ObjectGenericId = _objectgenericid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.MsgId);
			writer.Write(this.TimeStamp);
			writer.Write(this.Owner);
			writer.Write(this.ObjectGenericId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MsgId = reader.Read<CustomVar<short>>();
			this.TimeStamp = reader.Read<int>();
			this.Owner = reader.Read<string>();
			this.ObjectGenericId = reader.Read<CustomVar<short>>();

		}


	}
}
