//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class MimicryObjectPreviewMessage : IDofusMessage
	{
		public  const int NetworkId = 6458;
		public  int ProtocolId { get { return NetworkId; } }

		public ObjectItem Result { get; set; }


		public MimicryObjectPreviewMessage() { }


		public MimicryObjectPreviewMessage InitMimicryObjectPreviewMessage(ObjectItem _result)
		{

			this.Result = _result;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Result.Serialize());

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Result = new ObjectItem();
			this.Result.Deserialize(reader);

		}


	}
}
