//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class ObjectMovementMessage : IDofusMessage
	{
		public  const int NetworkId = 3010;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> ObjectUID { get; set; }

		public short Position { get; set; }


		public ObjectMovementMessage() { }


		public ObjectMovementMessage InitObjectMovementMessage(CustomVar<int> _objectuid, short _position)
		{

			this.ObjectUID = _objectuid;
			this.Position = _position;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.ObjectUID);
			writer.Write(this.Position);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ObjectUID = reader.Read<CustomVar<int>>();
			this.Position = reader.Read<short>();

		}


	}
}
