//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class ObjectsAddedMessage : IDofusMessage
	{
		public  const int NetworkId = 6033;
		public  int ProtocolId { get { return NetworkId; } }

		public ObjectItem[] Object { get; set; }


		public ObjectsAddedMessage() { }


		public ObjectsAddedMessage InitObjectsAddedMessage(ObjectItem[] _object)
		{

			this.Object = _object;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Object.Length));
			foreach(var obj in Object)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Object_length = reader.Read<short>();
			this.Object = new ObjectItem[Object_length];
			for(int i = 0; i < Object_length; i++)
			{
				this.Object[i] = new ObjectItem();
				this.Object[i].Deserialize(reader);
			}

		}


	}
}
