//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:53.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.data.items;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class ObjectsQuantityMessage : IDofusMessage
	{
		public  const int NetworkId = 6206;
		public  int ProtocolId { get { return NetworkId; } }

		public ObjectItemQuantity[] ObjectsUIDAndQty { get; set; }


		public ObjectsQuantityMessage() { }


		public ObjectsQuantityMessage InitObjectsQuantityMessage(ObjectItemQuantity[] _objectsuidandqty)
		{

			this.ObjectsUIDAndQty = _objectsuidandqty;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.ObjectsUIDAndQty.Length));
			var memory1 = new Memory<byte>[ObjectsUIDAndQty.Length];
			for(int i = 0; i < ObjectsUIDAndQty.Length; i++)
			{
				memory1[i] = this.ObjectsUIDAndQty[i].Serialize();
				size += memory1[i].Length;
			}


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData((short)(this.ObjectsUIDAndQty.Length));
			for(int i = 0; i < memory1.Length; i++)
			{
				writer.WriteDatas(memory1[i]);
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int ObjectsUIDAndQty_length = reader.Read<short>();
			this.ObjectsUIDAndQty = new ObjectItemQuantity[ObjectsUIDAndQty_length];
			for(int i = 0; i < ObjectsUIDAndQty_length; i++)
			{
				this.ObjectsUIDAndQty[i] = new ObjectItemQuantity();
				this.ObjectsUIDAndQty[i].Deserialize(reader);
			}

		}


	}
}
