//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:22.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.inventory.items
{
	public class SymbioticObjectAssociateRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6522;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> SymbioteUID { get; set; }

		public byte SymbiotePos { get; set; }

		public CustomVar<int> HostUID { get; set; }

		public byte HostPos { get; set; }


		public SymbioticObjectAssociateRequestMessage() { }


		public SymbioticObjectAssociateRequestMessage InitSymbioticObjectAssociateRequestMessage(CustomVar<int> _symbioteuid, byte _symbiotepos, CustomVar<int> _hostuid, byte _hostpos)
		{

			this.SymbioteUID = _symbioteuid;
			this.SymbiotePos = _symbiotepos;
			this.HostUID = _hostuid;
			this.HostPos = _hostpos;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.SymbioteUID);
			writer.Write(this.SymbiotePos);
			writer.Write(this.HostUID);
			writer.Write(this.HostPos);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SymbioteUID = reader.Read<CustomVar<int>>();
			this.SymbiotePos = reader.Read<byte>();
			this.HostUID = reader.Read<CustomVar<int>>();
			this.HostPos = reader.Read<byte>();

		}


	}
}
