//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:43.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.approach
{
	public class ServerSettingsMessage : IDofusMessage
	{
		public  const int NetworkId = 6340;
		public  int ProtocolId { get { return NetworkId; } }

		public string Lang { get; set; }

		public byte Community { get; set; }

		public byte GameType { get; set; }

		public WrappedBool IsMonoAccount { get; set; }

		public CustomVar<short> ArenaLeaveBanTime { get; set; }

		public int ItemMaxLevel { get; set; }

		public WrappedBool HasFreeAutopilot { get; set; }


		public ServerSettingsMessage() { }


		public ServerSettingsMessage InitServerSettingsMessage(string _lang, byte _community, byte _gametype, WrappedBool _ismonoaccount, CustomVar<short> _arenaleavebantime, int _itemmaxlevel, WrappedBool _hasfreeautopilot)
		{

			this.Lang = _lang;
			this.Community = _community;
			this.GameType = _gametype;
			this.IsMonoAccount = _ismonoaccount;
			this.ArenaLeaveBanTime = _arenaleavebantime;
			this.ItemMaxLevel = _itemmaxlevel;
			this.HasFreeAutopilot = _hasfreeautopilot;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Lang);
			size += DofusBinaryFactory.Sizing.SizeOf(Community);
			size += DofusBinaryFactory.Sizing.SizeOf(GameType);
			size++;
			size += DofusBinaryFactory.Sizing.SizeOf(ArenaLeaveBanTime);
			size += DofusBinaryFactory.Sizing.SizeOf(ItemMaxLevel);
			size++;


			using DofusWriter writer = new DofusWriter(size);

			byte box = 0;
			box = writer.SetFlag(box,0,this.IsMonoAccount);
			box = writer.SetFlag(box,1,this.HasFreeAutopilot);
			writer.WriteData(box);
			writer.WriteData(this.Lang);
			writer.WriteData(this.Community);
			writer.WriteData(this.GameType);
			writer.WriteData(this.ArenaLeaveBanTime);
			writer.WriteData(this.ItemMaxLevel);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			byte box = reader.Read<byte>();
			this.IsMonoAccount = reader.ReadFlag(box,0);
			this.HasFreeAutopilot = reader.ReadFlag(box,1);
			this.Lang = reader.Read<string>();
			this.Community = reader.Read<byte>();
			this.GameType = reader.Read<byte>();
			this.ArenaLeaveBanTime = reader.Read<CustomVar<short>>();
			this.ItemMaxLevel = reader.Read<int>();

		}


	}
}
