//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:12.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.interactive;

namespace Renaissance.Protocol.messages.game.interactive
{
	public class InteractiveMapUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 5002;
		public  int ProtocolId { get { return NetworkId; } }

		public InteractiveElement[] InteractiveElements { get; set; }


		public InteractiveMapUpdateMessage() { }


		public InteractiveMapUpdateMessage InitInteractiveMapUpdateMessage(InteractiveElement[] _interactiveelements)
		{

			this.InteractiveElements = _interactiveelements;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.InteractiveElements.Length));
			foreach(var obj in InteractiveElements)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int InteractiveElements_length = reader.Read<short>();
			this.InteractiveElements = new InteractiveElement[InteractiveElements_length];
			for(int i = 0; i < InteractiveElements_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.InteractiveElements[i] = new InteractiveElement();
				this.InteractiveElements[i].Deserialize(reader);
			}

		}


	}
}
