//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:26.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.stats
{
	public class StatsUpgradeRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 5610;
		public  int ProtocolId { get { return NetworkId; } }

		public bool UseAdditionnal { get; set; }

		public byte StatId { get; set; }

		public CustomVar<short> BoostPoint { get; set; }


		public StatsUpgradeRequestMessage() { }


		public StatsUpgradeRequestMessage InitStatsUpgradeRequestMessage(bool _useadditionnal, byte _statid, CustomVar<short> _boostpoint)
		{

			this.UseAdditionnal = _useadditionnal;
			this.StatId = _statid;
			this.BoostPoint = _boostpoint;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.UseAdditionnal);
			writer.Write(this.StatId);
			writer.Write(this.BoostPoint);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.UseAdditionnal = reader.Read<bool>();
			this.StatId = reader.Read<byte>();
			this.BoostPoint = reader.Read<CustomVar<short>>();

		}


	}
}
