//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:11.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.friend;

namespace Renaissance.Protocol.messages.game.friend
{
	public class IgnoredListMessage : IDofusMessage
	{
		public  const int NetworkId = 5674;
		public  int ProtocolId { get { return NetworkId; } }

		public IgnoredInformations[] IgnoredList { get; set; }


		public IgnoredListMessage() { }


		public IgnoredListMessage InitIgnoredListMessage(IgnoredInformations[] _ignoredlist)
		{

			this.IgnoredList = _ignoredlist;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.IgnoredList.Length));
			foreach(var obj in IgnoredList)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int IgnoredList_length = reader.Read<short>();
			this.IgnoredList = new IgnoredInformations[IgnoredList_length];
			for(int i = 0; i < IgnoredList_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.IgnoredList[i] = new IgnoredInformations();
				this.IgnoredList[i].Deserialize(reader);
			}

		}


	}
}
