//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:11.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.friend;

namespace Renaissance.Protocol.messages.game.friend
{
	public class IgnoredAddedMessage : IDofusMessage
	{
		public  const int NetworkId = 5678;
		public  int ProtocolId { get { return NetworkId; } }

		public IgnoredInformations IgnoreAdded { get; set; }

		public bool Session { get; set; }


		public IgnoredAddedMessage() { }


		public IgnoredAddedMessage InitIgnoredAddedMessage(IgnoredInformations _ignoreadded, bool _session)
		{

			this.IgnoreAdded = _ignoreadded;
			this.Session = _session;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(IgnoreAdded.ProtocolId));
			writer.Write(this.IgnoreAdded.Serialize());
			writer.Write(this.Session);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

reader.Skip(2); // skip read short
			this.IgnoreAdded = new IgnoredInformations();
			this.IgnoreAdded.Deserialize(reader);
			this.Session = reader.Read<bool>();

		}


	}
}
