//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:20.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.externalnotifications
{
	[D2OClass("ExternalNotification", "com.ankamagames.dofus.datacenter.externalnotifications")]
	public class ExternalNotificationData : IDataCenter
	{

		private int m_id;
		private int m_categoryId;
		private int m_iconId;
		private int m_colorId;
		private uint m_descriptionId;
		private Boolean m_defaultEnable;
		private Boolean m_defaultSound;
		private Boolean m_defaultNotify;
		private Boolean m_defaultMultiAccount;
		private String m_name;
		private uint m_messageId;

		public int Id
		{
			get => m_id;
			set => m_id = value;
		}

		public int CategoryId
		{
			get => m_categoryId;
			set => m_categoryId = value;
		}

		public int IconId
		{
			get => m_iconId;
			set => m_iconId = value;
		}

		public int ColorId
		{
			get => m_colorId;
			set => m_colorId = value;
		}

		public uint DescriptionId
		{
			get => m_descriptionId;
			set => m_descriptionId = value;
		}

		public Boolean DefaultEnable
		{
			get => m_defaultEnable;
			set => m_defaultEnable = value;
		}

		public Boolean DefaultSound
		{
			get => m_defaultSound;
			set => m_defaultSound = value;
		}

		public Boolean DefaultNotify
		{
			get => m_defaultNotify;
			set => m_defaultNotify = value;
		}

		public Boolean DefaultMultiAccount
		{
			get => m_defaultMultiAccount;
			set => m_defaultMultiAccount = value;
		}

		public String Name
		{
			get => m_name;
			set => m_name = value;
		}

		public uint MessageId
		{
			get => m_messageId;
			set => m_messageId = value;
		}


	}
}
