//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:58.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.dare
{
	public class DareVersatileInformations : IDofusType
	{
		public  const int NetworkId = 504;
		public  int ProtocolId { get { return NetworkId; } }

		public double DareId { get; set; }

		public int CountEntrants { get; set; }

		public int CountWinners { get; set; }


		public DareVersatileInformations() { }


		public DareVersatileInformations InitDareVersatileInformations(double _dareid, int _countentrants, int _countwinners)
		{

			this.DareId = _dareid;
			this.CountEntrants = _countentrants;
			this.CountWinners = _countwinners;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(DareId);
			size += DofusBinaryFactory.Sizing.SizeOf(CountEntrants);
			size += DofusBinaryFactory.Sizing.SizeOf(CountWinners);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.DareId);
			writer.WriteData(this.CountEntrants);
			writer.WriteData(this.CountWinners);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.DareId = reader.Read<double>();
			this.CountEntrants = reader.Read<int>();
			this.CountWinners = reader.Read<int>();

		}


	}
}
