//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:48.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.messages.game.actions;

namespace Renaissance.Protocol.messages.game.actions.fight
{
	public class GameActionFightTackledMessage : AbstractGameActionMessage, IDofusMessage
	{
		public new const int NetworkId = 1004;
		public new int ProtocolId { get { return NetworkId; } }

		public double[] TacklersIds { get; set; }


		public GameActionFightTackledMessage() { }


		public GameActionFightTackledMessage InitGameActionFightTackledMessage(CustomVar<short> _actionid, double _sourceid, double[] _tacklersids)
		{

			base.ActionId = _actionid;
			base.SourceId = _sourceid;
			this.TacklersIds = _tacklersids;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.TacklersIds.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(TacklersIds);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData((short)(this.TacklersIds.Length));
			writer.WriteDatas(TacklersIds);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			int TacklersIds_length = reader.Read<short>();
			this.TacklersIds = new double[TacklersIds_length];
			for(int i = 0; i < TacklersIds_length; i++)
				this.TacklersIds[i] = reader.Read<double>();

		}


	}
}
