//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:15.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.actions.fight
{
	public class GameActionFightCloseCombatMessage : AbstractGameActionFightTargetedAbilityMessage, IDofusMessage
	{
		public new const int NetworkId = 6116;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> WeaponGenericId { get; set; }


		public GameActionFightCloseCombatMessage() { }


		public GameActionFightCloseCombatMessage InitGameActionFightCloseCombatMessage(CustomVar<short> _weapongenericid)
		{

			this.WeaponGenericId = _weapongenericid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.WeaponGenericId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.WeaponGenericId = reader.Read<CustomVar<short>>();

		}


	}
}
