//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.messages.game.actions;
using    Renaissance.Protocol.types.game.actions.fight;

namespace Renaissance.Protocol.messages.game.actions.fight
{
	public class GameActionFightDispellableEffectMessage : AbstractGameActionMessage, IDofusMessage
	{
		public new const int NetworkId = 6070;
		public new int ProtocolId { get { return NetworkId; } }

		public AbstractFightDispellableEffect Effect { get; set; }


		public GameActionFightDispellableEffectMessage() { }


		public GameActionFightDispellableEffectMessage InitGameActionFightDispellableEffectMessage(CustomVar<short> _actionid, double _sourceid, AbstractFightDispellableEffect _effect)
		{

			base.ActionId = _actionid;
			base.SourceId = _sourceid;
			this.Effect = _effect;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += 2;
			var serialized1 = this.Effect.Serialize();
			size += serialized1.Length;
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData((short)(Effect.ProtocolId));
			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			reader.Skip(2); // skip protocolManager.GetInstance(short)
			this.Effect = new AbstractFightDispellableEffect();
			this.Effect.Deserialize(reader);

		}


	}
}
