//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:25.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.paddock
{
	public class GameDataPlayFarmObjectAnimationMessage : IDofusMessage
	{
		public  const int NetworkId = 6026;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short>[] CellId { get; set; }


		public GameDataPlayFarmObjectAnimationMessage() { }


		public GameDataPlayFarmObjectAnimationMessage InitGameDataPlayFarmObjectAnimationMessage(CustomVar<short>[] _cellid)
		{

			this.CellId = _cellid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.CellId.Length));
			foreach(var item in CellId)
				writer.Write(item);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int CellId_length = reader.Read<short>();
			this.CellId = new CustomVar<short>[CellId_length];
			for(int i = 0; i < CellId_length; i++)
				this.CellId[i] = reader.Read<CustomVar<short>>();

		}


	}
}
