//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.npcs
{
	[D2OClass("NpcAction", "com.ankamagames.dofus.datacenter.npcs")]
	public class NpcActionData : IDataCenter
	{

		private int m_id;
		private int m_realId;
		private uint m_nameId;

		public int Id
		{
			get => m_id;
			set => m_id = value;
		}

		public int RealId
		{
			get => m_realId;
			set => m_realId = value;
		}

		public uint NameId
		{
			get => m_nameId;
			set => m_nameId = value;
		}


	}
}
