//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:13.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.prism;

namespace Renaissance.Protocol.messages.game.prism
{
	public class PrismsInfoValidMessage : IDofusMessage
	{
		public  const int NetworkId = 6451;
		public  int ProtocolId { get { return NetworkId; } }

		public PrismFightersInformation[] Fights { get; set; }


		public PrismsInfoValidMessage() { }


		public PrismsInfoValidMessage InitPrismsInfoValidMessage(PrismFightersInformation[] _fights)
		{

			this.Fights = _fights;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Fights.Length));
			foreach(var obj in Fights)
			{
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Fights_length = reader.Read<short>();
			this.Fights = new PrismFightersInformation[Fights_length];
			for(int i = 0; i < Fights_length; i++)
			{
				this.Fights[i] = new PrismFightersInformation();
				this.Fights[i].Deserialize(reader);
			}

		}


	}
}
