//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:46.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.prism
{
	public class PrismUseRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6041;
		public  int ProtocolId { get { return NetworkId; } }

		public byte ModuleToUse { get; set; }


		public PrismUseRequestMessage() { }


		public PrismUseRequestMessage InitPrismUseRequestMessage(byte _moduletouse)
		{

			this.ModuleToUse = _moduletouse;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(ModuleToUse);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.ModuleToUse);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ModuleToUse = reader.Read<byte>();

		}


	}
}
