//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:01.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.fight;

namespace Renaissance.Protocol.types.game.guild.tax
{
	public class TaxCollectorWaitingForHelpInformations : TaxCollectorComplementaryInformations, IDofusType
	{
		public new const int NetworkId = 447;
		public new int ProtocolId { get { return NetworkId; } }

		public ProtectedEntityWaitingForHelpInfo WaitingForHelpInfo { get; set; }


		public TaxCollectorWaitingForHelpInformations() { }


		public TaxCollectorWaitingForHelpInformations InitTaxCollectorWaitingForHelpInformations(ProtectedEntityWaitingForHelpInfo _waitingforhelpinfo)
		{

			this.WaitingForHelpInfo = _waitingforhelpinfo;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.WaitingForHelpInfo.Serialize();
			size += serialized1.Length;
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteDatas(serialized1);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.WaitingForHelpInfo = new ProtectedEntityWaitingForHelpInfo();
			this.WaitingForHelpInfo.Deserialize(reader);

		}


	}
}
