//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.web.ankabox
{
	public class MailStatusMessage : IDofusMessage
	{
		public  const int NetworkId = 6275;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Unread { get; set; }

		public CustomVar<short> Total { get; set; }


		public MailStatusMessage() { }


		public MailStatusMessage InitMailStatusMessage(CustomVar<short> _unread, CustomVar<short> _total)
		{

			this.Unread = _unread;
			this.Total = _total;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Unread);
			size += DofusBinaryFactory.Sizing.SizeOf(Total);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Unread);
			writer.WriteData(this.Total);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Unread = reader.Read<CustomVar<short>>();
			this.Total = reader.Read<CustomVar<short>>();

		}


	}
}
