//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.web.ankabox
{
	public class NewMailMessage : MailStatusMessage, IDofusMessage
	{
		public new const int NetworkId = 6292;
		public new int ProtocolId { get { return NetworkId; } }

		public int[] SendersAccountId { get; set; }


		public NewMailMessage() { }


		public NewMailMessage InitNewMailMessage(CustomVar<short> _unread, CustomVar<short> _total, int[] _sendersaccountid)
		{

			base.Unread = _unread;
			base.Total = _total;
			this.SendersAccountId = _sendersaccountid;

			return this;
		}

		public new Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf((short)(this.SendersAccountId.Length));
			size += DofusBinaryFactory.Sizing.SizeOf(SendersAccountId);
			var parent = base.Serialize();
			size += parent.Length;


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(parent);
			writer.WriteData((short)(this.SendersAccountId.Length));
			writer.WriteDatas(SendersAccountId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			int SendersAccountId_length = reader.Read<short>();
			this.SendersAccountId = new int[SendersAccountId_length];
			for(int i = 0; i < SendersAccountId_length; i++)
				this.SendersAccountId[i] = reader.Read<int>();

		}


	}
}
