//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class SubArea
{

    public int Id { get; set; }

    public uint NameId { get; set; }

    public int AreaId { get; set; }

    public List<List<int>> Playlists { get; set; }

    public List<double> MapIds { get; set; }

    public Rectangle Bounds { get; set; }

    public List<int> Shape { get; set; }

    public int WorldmapId { get; set; }

    public List<uint> CustomWorldMap { get; set; }

    public int PackId { get; set; }

    public uint Level { get; set; }

    public bool IsConquestVillage { get; set; }

    public bool BasicAccountAllowed { get; set; }

    public bool DisplayOnWorldMap { get; set; }

    public bool MountAutoTripAllowed { get; set; }

    public bool PsiAllowed { get; set; }

    public List<uint> Monsters { get; set; }

    public bool Capturable { get; set; }

    public List<List<double>> Quests { get; set; }

    public List<List<double>> Npcs { get; set; }

    public List<int> Harvestables { get; set; }

    public int AssociatedZaapMapId { get; set; }

}