//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:21.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.monsters
{
	[D2OClass("MonsterGrade", "com.ankamagames.dofus.datacenter.monsters")]
	public class MonsterGradeData : IDataCenter
	{

		private uint m_grade;
		private int m_monsterId;
		private uint m_level;
		private int m_vitality;
		private int m_paDodge;
		private int m_pmDodge;
		private int m_wisdom;
		private int m_earthResistance;
		private int m_airResistance;
		private int m_fireResistance;
		private int m_waterResistance;
		private int m_neutralResistance;
		private int m_gradeXp;
		private int m_lifePoints;
		private int m_actionPoints;
		private int m_movementPoints;
		private int m_damageReflect;
		private uint m_hiddenLevel;
		private int m_strength;
		private int m_intelligence;
		private int m_chance;
		private int m_agility;
		private int m_startingSpellId;

		public uint Grade
		{
			get => m_grade;
			set => m_grade = value;
		}

		public int MonsterId
		{
			get => m_monsterId;
			set => m_monsterId = value;
		}

		public uint Level
		{
			get => m_level;
			set => m_level = value;
		}

		public int Vitality
		{
			get => m_vitality;
			set => m_vitality = value;
		}

		public int PaDodge
		{
			get => m_paDodge;
			set => m_paDodge = value;
		}

		public int PmDodge
		{
			get => m_pmDodge;
			set => m_pmDodge = value;
		}

		public int Wisdom
		{
			get => m_wisdom;
			set => m_wisdom = value;
		}

		public int EarthResistance
		{
			get => m_earthResistance;
			set => m_earthResistance = value;
		}

		public int AirResistance
		{
			get => m_airResistance;
			set => m_airResistance = value;
		}

		public int FireResistance
		{
			get => m_fireResistance;
			set => m_fireResistance = value;
		}

		public int WaterResistance
		{
			get => m_waterResistance;
			set => m_waterResistance = value;
		}

		public int NeutralResistance
		{
			get => m_neutralResistance;
			set => m_neutralResistance = value;
		}

		public int GradeXp
		{
			get => m_gradeXp;
			set => m_gradeXp = value;
		}

		public int LifePoints
		{
			get => m_lifePoints;
			set => m_lifePoints = value;
		}

		public int ActionPoints
		{
			get => m_actionPoints;
			set => m_actionPoints = value;
		}

		public int MovementPoints
		{
			get => m_movementPoints;
			set => m_movementPoints = value;
		}

		public int DamageReflect
		{
			get => m_damageReflect;
			set => m_damageReflect = value;
		}

		public uint HiddenLevel
		{
			get => m_hiddenLevel;
			set => m_hiddenLevel = value;
		}

		public int Strength
		{
			get => m_strength;
			set => m_strength = value;
		}

		public int Intelligence
		{
			get => m_intelligence;
			set => m_intelligence = value;
		}

		public int Chance
		{
			get => m_chance;
			set => m_chance = value;
		}

		public int Agility
		{
			get => m_agility;
			set => m_agility = value;
		}

		public int StartingSpellId
		{
			get => m_startingSpellId;
			set => m_startingSpellId = value;
		}


	}
}
