//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:12.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.house
{
	public class HouseTeleportRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 6726;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> HouseId { get; set; }

		public int HouseInstanceId { get; set; }


		public HouseTeleportRequestMessage() { }


		public HouseTeleportRequestMessage InitHouseTeleportRequestMessage(CustomVar<int> _houseid, int _houseinstanceid)
		{

			this.HouseId = _houseid;
			this.HouseInstanceId = _houseinstanceid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.HouseId);
			writer.Write(this.HouseInstanceId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.HouseId = reader.Read<CustomVar<int>>();
			this.HouseInstanceId = reader.Read<int>();

		}


	}
}
