// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renaissance.World.Database.Maps.Positions;

namespace Renaissance.World.Migrations.MapPosition
{
    [DbContext(typeof(MapPositionContext))]
    [Migration("20191228212952_MapsPositionPatched")]
    partial class MapsPositionPatched
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Renaissance.World.Database.Maps.Positions.MapPosition", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("double precision");

                    b.Property<int>("Capabilities")
                        .HasColumnType("integer");

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.Property<bool>("Outdoor")
                        .HasColumnType("boolean");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MapsPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
