//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:27.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.roleplay.houses.guild
{
	public class HouseGuildRightsViewMessage : IDofusMessage
	{
		public  const int NetworkId = 5700;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<int> HouseId { get; set; }

		public int InstanceId { get; set; }


		public HouseGuildRightsViewMessage() { }


		public HouseGuildRightsViewMessage InitHouseGuildRightsViewMessage(CustomVar<int> _houseid, int _instanceid)
		{

			this.HouseId = _houseid;
			this.InstanceId = _instanceid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.HouseId);
			writer.Write(this.InstanceId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.HouseId = reader.Read<CustomVar<int>>();
			this.InstanceId = reader.Read<int>();

		}


	}
}
