//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:23.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.context.fight.challenge
{
	public class ChallengeResultMessage : IDofusMessage
	{
		public  const int NetworkId = 6019;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> ChallengeId { get; set; }

		public bool Success { get; set; }


		public ChallengeResultMessage() { }


		public ChallengeResultMessage InitChallengeResultMessage(CustomVar<short> _challengeid, bool _success)
		{

			this.ChallengeId = _challengeid;
			this.Success = _success;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.ChallengeId);
			writer.Write(this.Success);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.ChallengeId = reader.Read<CustomVar<short>>();
			this.Success = reader.Read<bool>();

		}


	}
}
