//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:46.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum AllianceRightsBitEnum
   {
      
       ALLIANCE_RIGHT_NONE = 0,
      
       ALLIANCE_RIGHT_BOSS = 1,
      
       ALLIANCE_RIGHT_MANAGE_PRISMS = 2,
      
       ALLIANCE_RIGHT_TALK_IN_CHAN = 4,
      
       ALLIANCE_RIGHT_RECRUIT_GUILDS = 8,
      
       ALLIANCE_RIGHT_KICK_GUILDS = 16,
      
       ALLIANCE_RIGHT_MANAGE_RIGHTS = 32
       
      
   }
}
