//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:46.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum CharacterRemodelingEnum
   {
      
       CHARACTER_REMODELING_NOT_APPLICABLE = 0,
      
       CHARACTER_REMODELING_NAME = 1,
      
       CHARACTER_REMODELING_COLORS = 2,
      
       CHARACTER_REMODELING_COSMETIC = 4,
      
       CHARACTER_REMODELING_BREED = 8,
      
       CHARACTER_REMODELING_GENDER = 16,
      
       CHARACTER_OPT_REMODELING_NAME = 32,
      
       CHARACTER_OPT_REMODELING_ALL = 64
       
      
   }
}
