//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:46.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum CraftResultEnum
   {
      
       CRAFT_IMPOSSIBLE = 0,
      
       CRAFT_FAILED = 1,
      
       CRAFT_SUCCESS = 2,
      
       CRAFT_NEUTRAL = 3,
      
       CRAFT_FORBIDDEN = 4
       
      
   }
}
