//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum PartyNameErrorEnum
   {
      
       PARTY_NAME_UNDEFINED_ERROR = 0,
      
       PARTY_NAME_INVALID = 1,
      
       PARTY_NAME_ALREADY_USED = 2,
      
       PARTY_NAME_UNALLOWED_RIGHTS = 3,
      
       PARTY_NAME_UNALLOWED_NOW = 4
       
      
   }
}
