//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum PvpArenaStepEnum
   {
      
       ARENA_STEP_REGISTRED = 0,
      
       ARENA_STEP_WAITING_FIGHT = 1,
      
       ARENA_STEP_STARTING_FIGHT = 2,
      
       ARENA_STEP_UNREGISTER = 3
       
      
   }
}
