//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum ServerStatusEnum
   {
      
       STATUS_UNKNOWN = 0,
      
       OFFLINE = 1,
      
       STARTING = 2,
      
       ONLINE = 3,
      
       NOJOIN = 4,
      
       SAVING = 5,
      
       STOPING = 6,
      
       FULL = 7
       
      
   }
}
