//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 30/10/2019 08:58:47.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Renaissance.Protocol.enums
{
   public enum TaxCollectorMovementTypeEnum
   {
      
       TAX_COLLECTOR_UNKNOWN_ACTION = 0,
      
       TAX_COLLECTOR_HIRED = 1,
      
       TAX_COLLECTOR_HARVESTED = 2,
      
       TAX_COLLECTOR_DEFEATED = 3,
      
       TAX_COLLECTOR_DESTROYED = 4
       
      
   }
}
