//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.guild.tax;

namespace Renaissance.Protocol.messages.game.guild.tax
{
	public class AbstractTaxCollectorListMessage : IDofusMessage
	{
		public  const int NetworkId = 6568;
		public  int ProtocolId { get { return NetworkId; } }

		public TaxCollectorInformations[] Informations { get; set; }


		public AbstractTaxCollectorListMessage() { }


		public AbstractTaxCollectorListMessage InitAbstractTaxCollectorListMessage(TaxCollectorInformations[] _informations)
		{

			this.Informations = _informations;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write((short)(this.Informations.Length));
			foreach(var obj in Informations)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			int Informations_length = reader.Read<short>();
			this.Informations = new TaxCollectorInformations[Informations_length];
			for(int i = 0; i < Informations_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.Informations[i] = new TaxCollectorInformations();
				this.Informations[i].Deserialize(reader);
			}

		}


	}
}
