//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.guild.tax
{
	public class GuildFightLeaveRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 5715;
		public  int ProtocolId { get { return NetworkId; } }

		public double TaxCollectorId { get; set; }

		public CustomVar<long> CharacterId { get; set; }


		public GuildFightLeaveRequestMessage() { }


		public GuildFightLeaveRequestMessage InitGuildFightLeaveRequestMessage(double _taxcollectorid, CustomVar<long> _characterid)
		{

			this.TaxCollectorId = _taxcollectorid;
			this.CharacterId = _characterid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.TaxCollectorId);
			writer.Write(this.CharacterId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.TaxCollectorId = reader.Read<double>();
			this.CharacterId = reader.Read<CustomVar<long>>();

		}


	}
}
