//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.character;
using    Renaissance.Protocol.types.game.fight;

namespace Renaissance.Protocol.types.game.prism
{
	public class PrismFightersInformation : IDofusType
	{
		public  const int NetworkId = 443;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> SubAreaId { get; set; }

		public ProtectedEntityWaitingForHelpInfo WaitingForHelpInfo { get; set; }

		public CharacterMinimalPlusLookInformations[] AllyCharactersInformations { get; set; }

		public CharacterMinimalPlusLookInformations[] EnemyCharactersInformations { get; set; }


		public PrismFightersInformation() { }


		public PrismFightersInformation InitPrismFightersInformation(CustomVar<short> _subareaid, ProtectedEntityWaitingForHelpInfo _waitingforhelpinfo, CharacterMinimalPlusLookInformations[] _allycharactersinformations, CharacterMinimalPlusLookInformations[] _enemycharactersinformations)
		{

			this.SubAreaId = _subareaid;
			this.WaitingForHelpInfo = _waitingforhelpinfo;
			this.AllyCharactersInformations = _allycharactersinformations;
			this.EnemyCharactersInformations = _enemycharactersinformations;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.SubAreaId);
			writer.Write(this.WaitingForHelpInfo.Serialize());
			writer.Write((short)(this.AllyCharactersInformations.Length));
			foreach(var obj in AllyCharactersInformations)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}
			writer.Write((short)(this.EnemyCharactersInformations.Length));
			foreach(var obj in EnemyCharactersInformations)
			{
				writer.Write((short)(obj.ProtocolId));
				writer.Write(obj.Serialize());
			}

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SubAreaId = reader.Read<CustomVar<short>>();
			this.WaitingForHelpInfo = new ProtectedEntityWaitingForHelpInfo();
			this.WaitingForHelpInfo.Deserialize(reader);
			int AllyCharactersInformations_length = reader.Read<short>();
			this.AllyCharactersInformations = new CharacterMinimalPlusLookInformations[AllyCharactersInformations_length];
			for(int i = 0; i < AllyCharactersInformations_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.AllyCharactersInformations[i] = new CharacterMinimalPlusLookInformations();
				this.AllyCharactersInformations[i].Deserialize(reader);
			}
			int EnemyCharactersInformations_length = reader.Read<short>();
			this.EnemyCharactersInformations = new CharacterMinimalPlusLookInformations[EnemyCharactersInformations_length];
			for(int i = 0; i < EnemyCharactersInformations_length; i++)
			{
reader.Skip(2); // skip read short for protocolManager.GetInstance(short)
				this.EnemyCharactersInformations[i] = new CharacterMinimalPlusLookInformations();
				this.EnemyCharactersInformations[i].Deserialize(reader);
			}

		}


	}
}
