//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:41.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.subscription
{
	public class AccountInformationsUpdateMessage : IDofusMessage
	{
		public  const int NetworkId = 6740;
		public  int ProtocolId { get { return NetworkId; } }

		public double SubscriptionEndDate { get; set; }

		public double UnlimitedRestatEndDate { get; set; }


		public AccountInformationsUpdateMessage() { }


		public AccountInformationsUpdateMessage InitAccountInformationsUpdateMessage(double _subscriptionenddate, double _unlimitedrestatenddate)
		{

			this.SubscriptionEndDate = _subscriptionenddate;
			this.UnlimitedRestatEndDate = _unlimitedrestatenddate;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(SubscriptionEndDate);
			size += DofusBinaryFactory.Sizing.SizeOf(UnlimitedRestatEndDate);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.SubscriptionEndDate);
			writer.WriteData(this.UnlimitedRestatEndDate);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.SubscriptionEndDate = reader.Read<double>();
			this.UnlimitedRestatEndDate = reader.Read<double>();

		}


	}
}
