//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 27/12/2019 11:41:19.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    System.Collections.Generic;
using    Renaissance.Protocol.datacenter.geometry;

namespace Renaissance.Protocol.datacenter.alignments
{
	[D2OClass("AlignmentRankJntGift", "com.ankamagames.dofus.datacenter.alignments")]
	public class AlignmentRankJntGiftData : IDataCenter
	{

		private int m_id;
		private List<int> m_gifts;
		private List<int> m_parameters;
		private List<int> m_levels;

		public int Id
		{
			get => m_id;
			set => m_id = value;
		}

		public List<int> Gifts
		{
			get => m_gifts;
			set => m_gifts = value;
		}

		public List<int> Parameters
		{
			get => m_parameters;
			set => m_parameters = value;
		}

		public List<int> Levels
		{
			get => m_levels;
			set => m_levels = value;
		}


	}
}
