//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:50:43.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.basic
{
	public class BasicWhoAmIRequestMessage : IDofusMessage
	{
		public  const int NetworkId = 5664;
		public  int ProtocolId { get { return NetworkId; } }

		public bool Verbose { get; set; }


		public BasicWhoAmIRequestMessage() { }


		public BasicWhoAmIRequestMessage InitBasicWhoAmIRequestMessage(bool _verbose)
		{

			this.Verbose = _verbose;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			size += DofusBinaryFactory.Sizing.SizeOf(Verbose);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteData(this.Verbose);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Verbose = reader.Read<bool>();

		}


	}
}
