//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:09.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.basic
{
	public class NumericWhoIsMessage : IDofusMessage
	{
		public  const int NetworkId = 6297;
		public  int ProtocolId { get { return NetworkId; } }

		public CustomVar<long> PlayerId { get; set; }

		public int AccountId { get; set; }


		public NumericWhoIsMessage() { }


		public NumericWhoIsMessage InitNumericWhoIsMessage(CustomVar<long> _playerid, int _accountid)
		{

			this.PlayerId = _playerid;
			this.AccountId = _accountid;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.PlayerId);
			writer.Write(this.AccountId);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.PlayerId = reader.Read<CustomVar<long>>();
			this.AccountId = reader.Read<int>();

		}


	}
}
