//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:09.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.messages.game.basic
{
	public class TextInformationMessage : IDofusMessage
	{
		public  const int NetworkId = 780;
		public  int ProtocolId { get { return NetworkId; } }

		public byte MsgType { get; set; }

		public CustomVar<short> MsgId { get; set; }

		public string[] Parameters { get; set; }


		public TextInformationMessage() { }


		public TextInformationMessage InitTextInformationMessage(byte _msgtype, CustomVar<short> _msgid, string[] _parameters)
		{

			this.MsgType = _msgtype;
			this.MsgId = _msgid;
			this.Parameters = _parameters;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.MsgType);
			writer.Write(this.MsgId);
			writer.Write((short)(this.Parameters.Length));
			foreach(var item in Parameters)
				writer.Write(item);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.MsgType = reader.Read<byte>();
			this.MsgId = reader.Read<CustomVar<short>>();
			int Parameters_length = reader.Read<short>();
			this.Parameters = new string[Parameters_length];
			for(int i = 0; i < Parameters_length; i++)
				this.Parameters[i] = reader.Read<string>();

		}


	}
}
