//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 2/19/2022 5:49:39 PM.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Collections.Generic;

namespace StumpR.Protocol.Datacenter;

public class Quest
{

    public uint Id { get; set; }

    public uint NameId { get; set; }

    public List<uint> StepIds { get; set; }

    public uint CategoryId { get; set; }

    public uint RepeatType { get; set; }

    public uint RepeatLimit { get; set; }

    public bool IsDungeonQuest { get; set; }

    public uint LevelMin { get; set; }

    public uint LevelMax { get; set; }

    public bool IsPartyQuest { get; set; }

    public string StartCriterion { get; set; }

    public bool Followable { get; set; }

}