//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:28.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.shortcut
{
	public class Shortcut : IDofusType
	{
		public  const int NetworkId = 369;
		public  int ProtocolId { get { return NetworkId; } }

		public byte Slot { get; set; }


		public Shortcut() { }


		public Shortcut InitShortcut(byte _slot)
		{

			this.Slot = _slot;

			return this;
		}

		public  byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(this.Slot);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Slot = reader.Read<byte>();

		}


	}
}
