//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:29.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.shortcut
{
	public class ShortcutSmiley : Shortcut, IDofusType
	{
		public new const int NetworkId = 388;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> SmileyId { get; set; }


		public ShortcutSmiley() { }


		public ShortcutSmiley InitShortcutSmiley(CustomVar<short> _smileyid)
		{

			this.SmileyId = _smileyid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.SmileyId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.SmileyId = reader.Read<CustomVar<short>>();

		}


	}
}
