//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:27.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context
{
	public class MapCoordinatesExtended : MapCoordinatesAndId, IDofusType
	{
		public new const int NetworkId = 176;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> SubAreaId { get; set; }


		public MapCoordinatesExtended() { }


		public MapCoordinatesExtended InitMapCoordinatesExtended(CustomVar<short> _subareaid)
		{

			this.SubAreaId = _subareaid;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.SubAreaId);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.SubAreaId = reader.Read<CustomVar<short>>();

		}


	}
}
