//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 08/12/2019 12:51:02.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    System;
using    Renaissance.Binary;
using    Renaissance.Binary.Definition;

namespace Renaissance.Protocol.types.game.context.roleplay.party
{
	public class NamedPartyTeamWithOutcome : IDofusType
	{
		public  const int NetworkId = 470;
		public  int ProtocolId { get { return NetworkId; } }

		public NamedPartyTeam Team { get; set; }

		public CustomVar<short> Outcome { get; set; }


		public NamedPartyTeamWithOutcome() { }


		public NamedPartyTeamWithOutcome InitNamedPartyTeamWithOutcome(NamedPartyTeam _team, CustomVar<short> _outcome)
		{

			this.Team = _team;
			this.Outcome = _outcome;

			return this;
		}

		public  Memory<byte> Serialize()
		{

			int size = default;

			var serialized1 = this.Team.Serialize();
			size += serialized1.Length;
			size += DofusBinaryFactory.Sizing.SizeOf(Outcome);


			using DofusWriter writer = new DofusWriter(size);

			writer.WriteDatas(serialized1);
			writer.WriteData(this.Outcome);

			return writer.Data;
		}

		public  void Deserialize(DofusReader reader)
		{

			this.Team = new NamedPartyTeam();
			this.Team.Deserialize(reader);
			this.Outcome = reader.Read<CustomVar<short>>();

		}


	}
}
