//-------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool.
//  Generated on 07/11/2019 23:09:31.
//	Changes to this file may cause incorrect behavior !
//  Author : Scheduler.
// </auto-generated>
//-------------------------------------------------------------------------------

using    Renaissance.Binary;
using    Renaissance.Binary.Definition;
using    Renaissance.Protocol.types.game.character.status;
using    Renaissance.Protocol.types.game.context.roleplay.party.entity;
using    Renaissance.Protocol.types.game.look;

namespace Renaissance.Protocol.types.game.context.roleplay.party
{
	public class PartyMemberArenaInformations : PartyMemberInformations, IDofusType
	{
		public new const int NetworkId = 391;
		public new int ProtocolId { get { return NetworkId; } }

		public CustomVar<short> Rank { get; set; }


		public PartyMemberArenaInformations() { }


		public PartyMemberArenaInformations InitPartyMemberArenaInformations(CustomVar<short> _rank)
		{

			this.Rank = _rank;

			return this;
		}

		public new byte[] Serialize()
		{

			using DofusWriter writer = new DofusWriter();

			writer.Write(base.Serialize());
			writer.Write(this.Rank);

			return writer.Data;
		}

		public new void Deserialize(DofusReader reader)
		{

			base.Deserialize(reader);
			this.Rank = reader.Read<CustomVar<short>>();

		}


	}
}
